/*====================================================================
Retail SQL Business Analysis Portfolio
File: 08_join_analysis.sql

Phase 5: Relational Analysis (JOINs)

Investigation 14: Customer Purchasing Behaviour Analysis

Objective:
Analyse customer purchasing behaviour by combining customer,
order and payment information to identify purchasing frequency,
customer spending patterns, geographic behaviour and customer value.

Tables Used:
- customers
- orders
- order_payments

Relationship Path

customers
(customer_id)
      │
      ▼
orders
(order_id)
      │
      ▼
order_payments

/*---------------------------------------------------------------
SECTION A – PURCHASE FREQUENCY
---------------------------------------------------------------*/


/* Q1. How many orders has each unique customer placed? */

SELECT
    c.customer_unique_id AS customer,
    COUNT(o.order_id) AS total_orders
FROM orders AS o
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
ORDER BY total_orders DESC;


/* Q2. Top 10 customers with the highest number of orders */

SELECT
    c.customer_unique_id AS customer,
    COUNT(o.order_id) AS total_orders
FROM orders AS o
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
ORDER BY total_orders DESC
LIMIT 10;


/* Q3. How many unique customers have placed orders? */

SELECT
    COUNT(DISTINCT c.customer_unique_id) AS unique_customers
FROM orders AS o
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id;


/* Q4. How many orders has each customer placed within each state? */

SELECT
    c.customer_state,
    c.customer_unique_id AS customer,
    COUNT(o.order_id) AS total_orders
FROM orders AS o
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY
    c.customer_state,
    c.customer_unique_id
ORDER BY
    c.customer_state,
    total_orders DESC;


/* Q5. Which states have the highest number of orders? */

SELECT
    c.customer_state,
    COUNT(o.order_id) AS total_orders
FROM orders AS o
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_state
ORDER BY total_orders DESC
LIMIT 10;



/*---------------------------------------------------------------
SECTION B – CUSTOMER SPENDING
---------------------------------------------------------------*/


/* Q6. Total revenue generated by each customer */

SELECT
    c.customer_unique_id AS customer,
    ROUND(SUM(op.payment_value),2) AS total_revenue
FROM order_payments AS op
INNER JOIN orders AS o
    ON op.order_id = o.order_id
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
ORDER BY total_revenue DESC;


/* Q7. Top 10 highest revenue customers */

SELECT
    c.customer_unique_id AS customer,
    ROUND(SUM(op.payment_value),2) AS total_revenue
FROM order_payments AS op
INNER JOIN orders AS o
    ON op.order_id = o.order_id
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
ORDER BY total_revenue DESC
LIMIT 10;


/* Q8. Average spending per customer
   (To be revisited using CTEs in Phase 6.) */

SELECT
    c.customer_unique_id AS customer,
    ROUND(AVG(op.payment_value),2) AS average_payment
FROM order_payments AS op
INNER JOIN orders AS o
    ON op.order_id = o.order_id
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
ORDER BY average_payment DESC;


/* Q9. Average order value for each customer */

SELECT
    c.customer_unique_id AS customer,
    ROUND(
        SUM(op.payment_value) /
        COUNT(DISTINCT o.order_id),
        2
    ) AS average_order_value
FROM order_payments AS op
INNER JOIN orders AS o
    ON op.order_id = o.order_id
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
ORDER BY average_order_value DESC;



/*---------------------------------------------------------------
SECTION C – GEOGRAPHIC BEHAVIOUR
---------------------------------------------------------------*/


/* Q10. Which states have the highest number of purchasing customers? */

SELECT
    c.customer_state,
    COUNT(DISTINCT c.customer_unique_id) AS purchasing_customers
FROM orders AS o
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_state
ORDER BY purchasing_customers DESC;


/* Q11. Which states generate the highest customer revenue? */

SELECT
    c.customer_state,
    COUNT(DISTINCT c.customer_unique_id) AS total_customers,
    ROUND(SUM(op.payment_value),2) AS total_revenue
FROM order_payments AS op
INNER JOIN orders AS o
    ON op.order_id = o.order_id
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_state
ORDER BY total_revenue DESC;


/* Q12. Which cities have the highest average customer spending?
   (Metric refined in Phase 6.) */

SELECT
    c.customer_city,
    ROUND(AVG(op.payment_value),2) AS average_spending
FROM order_payments AS op
INNER JOIN orders AS o
    ON op.order_id = o.order_id
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_city
ORDER BY average_spending DESC;



/*---------------------------------------------------------------
SECTION D – CUSTOMER VALUE
---------------------------------------------------------------*/


/* Q13. Top 10 customers ranked by average order value */

SELECT
    c.customer_unique_id AS customer,
    ROUND(
        SUM(op.payment_value) /
        COUNT(DISTINCT o.order_id),
        2
    ) AS customer_value
FROM order_payments AS op
INNER JOIN orders AS o
    ON op.order_id = o.order_id
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
ORDER BY customer_value DESC
LIMIT 10;


/* Q14.
Percentage of total revenue generated by the Top 10 customers.

This analysis is intentionally deferred until Phase 6,
where Common Table Expressions (CTEs) and subqueries will
provide a cleaner and more maintainable solution.
*/


/* Q15. Customers with many orders but relatively low spending */

SELECT
    c.customer_unique_id AS customer,
    COUNT(DISTINCT o.order_id) AS total_orders,
    ROUND(
        SUM(op.payment_value) /
        COUNT(DISTINCT o.order_id),
        2
    ) AS average_order_value
FROM order_payments AS op
INNER JOIN orders AS o
    ON op.order_id = o.order_id
INNER JOIN customers AS c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
HAVING COUNT(DISTINCT o.order_id) >= 5
ORDER BY
    total_orders DESC,
    average_order_value ASC;