/*====================================================================
Retail SQL Business Analysis Portfolio

File: 10_seller_performance_analysis.sql

Phase 5 – Relational Analysis (JOINs)

Investigation 16: Seller Performance Analysis

Business Objective
------------------
Evaluate seller performance by analysing order fulfilment,
product diversity, revenue generation, geographic distribution,
and customer satisfaction.

Tables Used
-----------
- sellers
- order_items
- orders
- order_reviews
- products

Relationship Paths
------------------

Seller Activity & Revenue

sellers
(seller_id)
      │
      ▼
order_items
(order_id)
      │
      ▼
orders


Seller Reviews

sellers
(seller_id)
      │
      ▼
order_items
(order_id)
      │
      ▼
orders
(order_id)
      │
      ▼
order_reviews


Key Learning
------------
Revenue is calculated using order_items.price because price is
recorded at the individual product level.

Using order_payments.payment_value would duplicate revenue when
orders contain multiple products.

====================================================================*/



/*===============================================================
SECTION A – SELLER ACTIVITY
===============================================================*/


/*-----------------------------------------------------------------
Q1. How many delivered orders has each seller fulfilled?
-----------------------------------------------------------------*/

SELECT
    s.seller_id AS seller,
    COUNT(DISTINCT o.order_id) AS completed_orders
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
INNER JOIN orders AS o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY s.seller_id
ORDER BY completed_orders DESC;



/*-----------------------------------------------------------------
Q2. Top 10 most active sellers
-----------------------------------------------------------------*/

SELECT
    s.seller_id AS seller,
    COUNT(DISTINCT o.order_id) AS completed_orders
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
INNER JOIN orders AS o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY s.seller_id
ORDER BY completed_orders DESC
LIMIT 10;



/*-----------------------------------------------------------------
Q3. How many unique products does each seller offer?
-----------------------------------------------------------------*/

SELECT
    s.seller_id AS seller,
    COUNT(DISTINCT oi.product_id) AS unique_products
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_id
ORDER BY unique_products DESC;



/*-----------------------------------------------------------------
Q4. Top 10 sellers with the largest product catalogues
-----------------------------------------------------------------*/

SELECT
    s.seller_id AS seller,
    COUNT(DISTINCT oi.product_id) AS unique_products
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_id
ORDER BY unique_products DESC
LIMIT 10;



/*-----------------------------------------------------------------
Q5. Which states have the largest number of sellers?
-----------------------------------------------------------------*/

SELECT
    s.seller_state,
    COUNT(s.seller_id) AS total_sellers
FROM sellers AS s
GROUP BY s.seller_state
ORDER BY total_sellers DESC;





/*===============================================================
SECTION B – SELLER REVENUE
===============================================================*/


/*-----------------------------------------------------------------
Q6. Total revenue generated by each seller
-----------------------------------------------------------------*/

SELECT
    s.seller_id AS seller,
    ROUND(SUM(oi.price),2) AS total_revenue
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_id
ORDER BY total_revenue DESC;



/*-----------------------------------------------------------------
Q7. Top 10 highest-revenue sellers
-----------------------------------------------------------------*/

SELECT
    s.seller_id AS seller,
    ROUND(SUM(oi.price),2) AS total_revenue
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_id
ORDER BY total_revenue DESC
LIMIT 10;



/*-----------------------------------------------------------------
Q8. Average revenue generated per seller
-----------------------------------------------------------------*/

SELECT
    s.seller_id AS seller,
    ROUND(AVG(oi.price),2) AS average_revenue
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_id
ORDER BY average_revenue DESC;



/*-----------------------------------------------------------------
Q9. Which seller states generate the highest total revenue?
-----------------------------------------------------------------*/

SELECT
    s.seller_state,
    ROUND(SUM(oi.price),2) AS total_revenue
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_state
ORDER BY total_revenue DESC;



/*-----------------------------------------------------------------
Q10. Average revenue generated by seller state
-----------------------------------------------------------------*/

SELECT
    s.seller_state,
    ROUND(AVG(oi.price),2) AS average_revenue
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
GROUP BY s.seller_state
ORDER BY average_revenue DESC;





/*===============================================================
SECTION C – SELLER QUALITY
===============================================================*/


/*-----------------------------------------------------------------
Q11. Average review score received by each seller

NOTE:
Reviews are recorded at the order level. Joining reviews to
order_items may duplicate review scores for orders containing
multiple items. This limitation is acknowledged and revisited
in later project phases.
-----------------------------------------------------------------*/

SELECT
    s.seller_id AS seller,
    ROUND(AVG(r.review_score),2) AS average_review_score
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
INNER JOIN orders AS o
    ON oi.order_id = o.order_id
INNER JOIN order_reviews AS r
    ON o.order_id = r.order_id
GROUP BY s.seller_id
ORDER BY average_review_score DESC;



/*-----------------------------------------------------------------
Q12. Top 10 sellers with the highest average review score
-----------------------------------------------------------------*/

SELECT
    s.seller_id AS seller,
    ROUND(AVG(r.review_score),2) AS average_review_score
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
INNER JOIN orders AS o
    ON oi.order_id = o.order_id
INNER JOIN order_reviews AS r
    ON o.order_id = r.order_id
GROUP BY s.seller_id
ORDER BY average_review_score DESC
LIMIT 10;



/*-----------------------------------------------------------------
Q13. Sellers with high revenue and high customer satisfaction
-----------------------------------------------------------------*/

SELECT
    s.seller_id AS seller,
    ROUND(SUM(oi.price),2) AS total_revenue,
    ROUND(AVG(r.review_score),2) AS average_review_score
FROM sellers AS s
INNER JOIN order_items AS oi
    ON s.seller_id = oi.seller_id
INNER JOIN orders AS o
    ON oi.order_id = o.order_id
INNER JOIN order_reviews AS r
    ON o.order_id = r.order_id
GROUP BY s.seller_id
ORDER BY
    average_review_score DESC,
    total_revenue DESC;





/*===============================================================
SECTION D – BUSINESS INSIGHTS
===============================================================*/


/*-----------------------------------------------------------------
Q14. Strategic Seller Assessment

Strategic sellers should demonstrate:

• High order fulfilment
• Strong revenue generation
• Broad product catalogue
• Consistently high customer review scores

These sellers contribute significantly to both marketplace
performance and customer satisfaction.

-----------------------------------------------------------------*/



/*-----------------------------------------------------------------
Q15. Business Recommendations

• Develop strategic partnerships with consistently
  high-performing sellers.

• Introduce incentive programmes for sellers maintaining
  excellent customer satisfaction.

• Support lower-performing sellers through training
  and operational guidance.

• Monitor seller performance regularly using both
  financial and customer experience metrics.

• Build seller performance dashboards to support
  operational decision-making.

-----------------------------------------------------------------*/