/*
===============================================================================
Investigation 21: Payment Method & Customer Payment Behaviour Analysis
File: 15_payment_method_customer_payment_behaviour.sql
Project: Retail SQL Business Analysis
Database: PostgreSQL
Dataset: Brazilian E-Commerce Public Dataset by Olist
===============================================================================

BUSINESS OBJECTIVE
------------------
Analyze customer payment behaviour by examining payment methods,
installment usage, revenue contribution, and transaction values.

The objective is to understand customer payment preferences and provide
business insights that support payment optimization, customer experience,
and financial decision-making.

===============================================================================

DATABASE THINKING
-----------------

Primary Table
-------------
• order_payments

Supporting Table
----------------
• orders

Relationship Path
-----------------

orders
    │
order_id
    │
order_payments

Analysis Grain
--------------
Most questions in this investigation are analyzed at the payment-record level.

However, when measuring order-related KPIs, COUNT(DISTINCT order_id)
is used to avoid double-counting orders with multiple payment records.

===============================================================================

DATA QUALITY NOTES
------------------

• Revenue is calculated using order_payments.payment_value.

• The dataset contains a small number of records with the payment type
  'not_defined'. These records are retained during analysis but should be
  treated as exceptional cases rather than representative customer behaviour.

• An individual order may contain multiple payment records. Therefore,
  COUNT(DISTINCT order_id) is used whenever the business question concerns
  orders rather than payment transactions.

===============================================================================
QUESTION 1
Number of Payment Methods
===============================================================================

Business Question
-----------------
How many distinct payment methods exist in the dataset?

*/

SELECT

    COUNT(DISTINCT payment_type)
        AS payment_methods

FROM order_payments;



/*
===============================================================================
QUESTION 2
Payment Records by Payment Method
===============================================================================

Business Question
-----------------
How many payment records belong to each payment method?

*/

SELECT

    payment_type AS payment_method,

    COUNT(*) AS payment_records

FROM order_payments

GROUP BY payment_method

ORDER BY payment_records DESC;



/*
===============================================================================
QUESTION 3
Percentage Distribution of Payment Methods
===============================================================================

Business Question
-----------------
What percentage of all payment records does each payment method represent?

*/

SELECT

    payment_type AS payment_method,

    COUNT(*) AS payment_records,

    ROUND(

        COUNT(*) * 100.0 /

        (SELECT COUNT(*) FROM order_payments),

        2

    ) AS percentage_of_payment_records

FROM order_payments

GROUP BY payment_method

ORDER BY payment_records DESC;



/*
===============================================================================
QUESTION 4
Most Frequently Used Payment Method
===============================================================================

Business Question
-----------------
Which payment method is used most frequently?

*/

SELECT

    payment_type AS payment_method,

    COUNT(*) AS payment_records

FROM order_payments

GROUP BY payment_method

ORDER BY payment_records DESC

LIMIT 1;



/*
===============================================================================
QUESTION 5
Revenue by Payment Method
===============================================================================

Business Question
-----------------
How much revenue is generated by each payment method?

*/

SELECT

    payment_type AS payment_method,

    ROUND(

        SUM(payment_value),

        2

    ) AS total_revenue

FROM order_payments

GROUP BY payment_method

ORDER BY total_revenue DESC;



/*
===============================================================================
QUESTION 6
Highest Revenue Payment Method
===============================================================================

Business Question
-----------------
Which payment method generates the highest total revenue?

*/

SELECT

    payment_type AS payment_method,

    ROUND(

        SUM(payment_value),

        2

    ) AS total_revenue

FROM order_payments

GROUP BY payment_method

ORDER BY total_revenue DESC

LIMIT 1;



/*
===============================================================================
QUESTION 7
Average Payment Value by Payment Method
===============================================================================

Business Question
-----------------
What is the average payment value for each payment method?

*/

SELECT

    payment_type AS payment_method,

    ROUND(

        AVG(payment_value),

        2

    ) AS average_payment_value

FROM order_payments

GROUP BY payment_method

ORDER BY average_payment_value DESC;



/*
===============================================================================
QUESTION 8
Highest Average Payment Value
===============================================================================

Business Question
-----------------
Which payment method has the highest average payment value?

*/

SELECT

    payment_type AS payment_method,

    ROUND(

        AVG(payment_value),

        2

    ) AS average_payment_value

FROM order_payments

GROUP BY payment_method

ORDER BY average_payment_value DESC

LIMIT 1;



/*
===============================================================================
QUESTION 9
Average Installments by Payment Method
===============================================================================

Business Question
-----------------
What is the average number of installments used for each payment method?

*/

SELECT

    payment_type AS payment_method,

    ROUND(

        AVG(payment_installments),

        2

    ) AS average_installments

FROM order_payments

GROUP BY payment_method

ORDER BY average_installments DESC;



/*
===============================================================================
QUESTION 10
Maximum Installments by Payment Method
===============================================================================

Business Question
-----------------
What is the highest installment count recorded for each payment method?

*/

SELECT

    payment_type AS payment_method,

    MAX(payment_installments)
        AS maximum_installments

FROM order_payments

GROUP BY payment_method

ORDER BY maximum_installments DESC;



/*
===============================================================================
QUESTION 11
Single-Installment Payments
===============================================================================

Business Question
-----------------
How many payment records were completed using a single installment?

*/

SELECT

    COUNT(*) AS payment_records_with_single_installment

FROM order_payments

WHERE payment_installments = 1;



/*
===============================================================================
QUESTION 12
Multiple-Installment Payments
===============================================================================

Business Question
-----------------
How many payment records were completed using more than one installment?

*/

SELECT

    COUNT(*) AS payment_records_with_multiple_installments

FROM order_payments

WHERE payment_installments > 1;



/*
===============================================================================
END OF PART 1

Completed Questions

✓ Question 1
✓ Question 2
✓ Question 3
✓ Question 4
✓ Question 5
✓ Question 6
✓ Question 7
✓ Question 8
✓ Question 9
✓ Question 10
✓ Question 11
✓ Question 12

Part 2 continues with:

• Question 13
• Question 14
• Question 15
• Analyst Observations
• Business Insights
• Technical Skills Demonstrated
===============================================================================
*/