/*
===============================================================================
Investigation 22: Customer Retention & Repeat Purchase Analysis
File: 16_customer_retention_repeat_purchase_analysis.sql

Project:
Retail-SQL-Business-Analysis

Database:
PostgreSQL

Dataset:
Brazilian E-Commerce Public Dataset by Olist

Business Objective:
Analyse customer retention and purchasing behaviour by distinguishing between
one-time, repeat, and loyal customers. The investigation aims to measure
customer retention, evaluate customer lifetime contribution, identify
high-value customers, and provide actionable recommendations for improving
customer loyalty and long-term revenue growth.

Business Questions
------------------
1. How many unique customers does the business have?
2. How many customers placed exactly one order?
3. How many customers placed more than one order?
4. What percentage of customers are repeat customers?
5. Which customers placed the most orders?
6. What is the average number of orders per customer?
7. What is the maximum number of orders placed by a single customer?
8. Which customers generated the highest revenue?
9. How much revenue comes from repeat customers?
10. How much revenue comes from one-time customers?
11. Compare average revenue between one-time and repeat customers.
12. Segment customers based on purchasing frequency.
13. How many customers belong to each customer segment?
14. How much revenue is generated by each customer segment?
15. What business recommendations can improve customer retention?

Tables Used
-----------
- customers
- orders
- order_payments

Relationship Path
-----------------
customers
    └── customer_id
            │
            ▼
         orders
            └── order_id
                    │
                    ▼
             order_payments

Key Business Notes
------------------
• Customer retention analysis must always use customer_unique_id rather than
  customer_id because customer_id changes across multiple purchases while
  customer_unique_id represents the actual customer.

• Revenue is calculated using order_payments.payment_value because this
  investigation focuses on customer spending rather than product revenue.

===============================================================================
*/

-- ============================================================================
-- Question 1
-- How many unique customers does the business have?
-- ============================================================================

SELECT
    COUNT(DISTINCT customer_unique_id) AS unique_customers
FROM customers;

-- ============================================================================
-- Question 2
-- How many customers placed exactly one order?
-- ============================================================================

SELECT
    COUNT(*) AS one_time_customers
FROM (
    SELECT
        customers.customer_unique_id
    FROM customers
    JOIN orders
        ON customers.customer_id = orders.customer_id
    GROUP BY customers.customer_unique_id
    HAVING COUNT(DISTINCT orders.order_id) = 1
) AS one_time;

-- ============================================================================
-- Question 3
-- How many customers placed more than one order?
-- ============================================================================

SELECT
    COUNT(*) AS repeat_customers
FROM (
    SELECT
        customers.customer_unique_id
    FROM customers
    JOIN orders
        ON customers.customer_id = orders.customer_id
    GROUP BY customers.customer_unique_id
    HAVING COUNT(DISTINCT orders.order_id) > 1
) AS repeat_customers;

-- ============================================================================
-- Question 4
-- What percentage of customers are repeat customers?
-- ============================================================================

SELECT
    ROUND(
        COUNT(*) FILTER (
            WHERE total_orders > 1
        ) * 100.0
        / COUNT(*),
        2
    ) AS repeat_customer_percentage
FROM (
    SELECT
        customers.customer_unique_id,
        COUNT(DISTINCT orders.order_id) AS total_orders
    FROM customers
    JOIN orders
        ON customers.customer_id = orders.customer_id
    GROUP BY customers.customer_unique_id
) AS customer_orders;

-- ============================================================================
-- Question 5
-- Which customers placed the most orders?
-- ============================================================================

SELECT
    customers.customer_unique_id AS customer,
    COUNT(DISTINCT orders.order_id) AS number_of_orders
FROM customers
INNER JOIN orders
    ON customers.customer_id = orders.customer_id
GROUP BY customer
ORDER BY number_of_orders DESC
LIMIT 10;

-- ============================================================================
-- Question 6
-- What is the average number of orders per customer?
-- ============================================================================

SELECT
    ROUND(
        COUNT(DISTINCT orders.order_id)::NUMERIC
        / COUNT(DISTINCT customers.customer_unique_id),
        2
    ) AS average_orders_per_customer
FROM customers
INNER JOIN orders
    ON customers.customer_id = orders.customer_id;

-- ============================================================================
-- Question 7
-- What is the maximum number of orders placed by a single customer?
-- ============================================================================

SELECT
    customers.customer_unique_id AS customer,
    COUNT(DISTINCT orders.order_id) AS number_of_orders
FROM customers
INNER JOIN orders
    ON customers.customer_id = orders.customer_id
GROUP BY customer
ORDER BY number_of_orders DESC
LIMIT 1;

-- ============================================================================
-- Question 8
-- Which customers generated the highest revenue?
-- ============================================================================

SELECT
    customers.customer_unique_id AS customer,
    SUM(order_payments.payment_value) AS total_revenue
FROM customers
INNER JOIN orders
    ON customers.customer_id = orders.customer_id
INNER JOIN order_payments
    ON orders.order_id = order_payments.order_id
GROUP BY customer
ORDER BY total_revenue DESC
LIMIT 10;

-- ============================================================================
-- Question 9
-- How much revenue comes from repeat customers?
-- ============================================================================

SELECT
    ROUND(
        SUM(customer_revenue),
        2
    ) AS repeat_customer_revenue
FROM (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS total_orders,
        SUM(op.payment_value) AS customer_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_payments op
        ON o.order_id = op.order_id
    GROUP BY c.customer_unique_id
    HAVING COUNT(DISTINCT o.order_id) > 1
) AS repeat_customers;

-- ============================================================================
-- Question 10
-- How much revenue comes from one-time customers?
-- ============================================================================

SELECT
    ROUND(
        SUM(customer_revenue),
        2
    ) AS one_time_customer_revenue
FROM (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS total_orders,
        SUM(op.payment_value) AS customer_revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_payments op
        ON o.order_id = op.order_id
    GROUP BY c.customer_unique_id
    HAVING COUNT(DISTINCT o.order_id) = 1
) AS one_time_customers;

-- ============================================================================
-- Question 11
-- Compare the average revenue generated by one-time and repeat customers.
--
-- NOTE:
-- Revenue is first aggregated at the customer level before calculating
-- the average for each customer segment. This ensures the metric represents
-- average customer revenue rather than average payment value.
-- ============================================================================

SELECT
    customer_type,
    ROUND(
        AVG(customer_revenue),
        2
    ) AS average_customer_revenue
FROM (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS total_orders,
        SUM(op.payment_value) AS customer_revenue,
        CASE
            WHEN COUNT(DISTINCT o.order_id) = 1
                THEN 'One-Time Customer'
            ELSE 'Repeat Customer'
        END AS customer_type
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_payments op
        ON o.order_id = op.order_id
    GROUP BY c.customer_unique_id
) AS customer_summary
GROUP BY customer_type
ORDER BY average_customer_revenue DESC;

-- ============================================================================
-- Question 12
-- Segment customers according to purchasing behaviour.
-- ============================================================================

SELECT
    customer_category,
    COUNT(*) AS customers,
    ROUND(
        SUM(total_revenue),
        2
    ) AS total_revenue,
    ROUND(
        SUM(total_revenue) * 100.0
        / SUM(SUM(total_revenue)) OVER (),
        2
    ) AS revenue_percentage
FROM (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS total_orders,
        SUM(op.payment_value) AS total_revenue,
        CASE
            WHEN COUNT(DISTINCT o.order_id) = 1
                THEN 'One-Time Customer'

            WHEN COUNT(DISTINCT o.order_id) BETWEEN 2 AND 4
                THEN 'Repeat Customer'

            ELSE 'Loyal Customer'
        END AS customer_category
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_payments op
        ON o.order_id = op.order_id
    GROUP BY c.customer_unique_id
) AS customer_summary
GROUP BY customer_category
ORDER BY total_revenue DESC;

-- ============================================================================
-- Question 13
-- How many customers belong to each customer segment?
--
-- Interpretation:
-- The customer count from Question 12 provides the distribution of
-- customers across One-Time, Repeat and Loyal segments.
-- ============================================================================

-- (Derived directly from Question 12.)

-- ============================================================================
-- Question 14
-- How much revenue is generated by each customer segment?
--
-- Interpretation:
-- The revenue totals and revenue percentages calculated in Question 12
-- represent the contribution of each customer segment to overall sales.
-- ============================================================================

-- (Derived directly from Question 12.)

-- ============================================================================
-- Question 15
-- Business Recommendations
-- ============================================================================

/*

Analyst Observations
--------------------

• Customer retention is a critical driver of sustainable business growth.

• One-time customers contribute a significant proportion of total revenue,
  indicating strong customer acquisition but also highlighting an opportunity
  to improve repeat purchasing behaviour.

• Segmenting customers into One-Time, Repeat and Loyal groups enables more
  targeted marketing strategies and performance monitoring.

• Average customer revenue provides a better measure of customer value than
  average payment value because it reflects total spending per customer.

Business Recommendations
------------------------

1. Introduce second-purchase incentives to encourage newly acquired customers
   to make another purchase.

2. Implement loyalty programmes that reward repeat purchases with discounts,
   reward points or exclusive benefits.

3. Launch personalised email and SMS campaigns recommending complementary
   products shortly after a customer's first purchase.

4. Continuously monitor customer retention KPIs such as:
      - Repeat Purchase Rate
      - Average Orders per Customer
      - Revenue by Customer Segment
      - Customer Lifetime Value (CLV)

5. Use customer segmentation to tailor marketing campaigns according to
   purchasing behaviour rather than applying a single strategy to all
   customers.

===============================================================================
End of Investigation 22
===============================================================================

*/