/*
===============================================================================
Investigation 24: Common Table Expressions (CTEs) Business Analysis
File: 18_common_table_expressions_business_analysis.sql

Project:
Retail SQL Business Analysis (Brazilian E-Commerce Dataset)

Phase:
Phase 6 – Subqueries, Common Table Expressions (CTEs), and Views

Investigation:
24 – Common Table Expressions (CTEs)

Author:
Atsali Akolo

Database:
PostgreSQL

===============================================================================

BUSINESS OBJECTIVE
------------------
This investigation introduces Common Table Expressions (CTEs) as a powerful
technique for simplifying complex SQL queries.

Rather than repeating the same aggregations multiple times, CTEs allow
intermediate result sets to be defined once and reused throughout a query,
improving readability, maintainability, and scalability.

The investigation focuses on identifying high-performing customers, sellers,
product categories, and sales periods using reusable business summaries.

-------------------------------------------------------------------------------

LEARNING OBJECTIVES
-------------------
• Understand the syntax and purpose of Common Table Expressions (CTEs)
• Compare CTEs with nested subqueries
• Build reusable business summary tables
• Improve SQL readability and maintainability
• Chain multiple CTEs together
• Produce cleaner analytical reports

-------------------------------------------------------------------------------

RELATIONSHIP PATHS
------------------

Customer Revenue

customers
    ↓
orders
    ↓
order_payments

Seller Revenue

sellers
    ↓
order_items

Category Revenue

products
    ↓
order_items

Monthly Revenue

orders
    ↓
order_payments

===============================================================================
*/


/*=============================================================================
Question 1
Business Question:
Create a reusable CTE that calculates total revenue generated by each customer.
=============================================================================*/

WITH customer_revenue AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS revenue
    FROM order_payments op
    JOIN orders o
        ON op.order_id = o.order_id
    JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY customer
);


/*=============================================================================
Question 2
Business Question:
Identify customers whose revenue exceeds the average customer revenue.
=============================================================================*/

WITH customer_revenue AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS revenue
    FROM order_payments op
    JOIN orders o
        ON op.order_id = o.order_id
    JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY customer
)

SELECT *
FROM customer_revenue
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM customer_revenue
)
ORDER BY revenue DESC;


/*=============================================================================
Question 3
Business Question:
Retrieve the top 10 highest-spending customers.
=============================================================================*/

WITH customer_revenue AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS revenue
    FROM order_payments op
    JOIN orders o
        ON op.order_id = o.order_id
    JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY customer
)

SELECT *
FROM customer_revenue
ORDER BY revenue DESC
LIMIT 10;


/*=============================================================================
Question 4
Business Question:
Summarise customer revenue by calculating the average, highest,
and lowest customer revenue.
=============================================================================*/

WITH customer_revenue AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS revenue
    FROM order_payments op
    JOIN orders o
        ON op.order_id = o.order_id
    JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY customer
)

SELECT
    ROUND(AVG(revenue), 2) AS average_customer_revenue,
    MAX(revenue) AS highest_customer_revenue,
    MIN(revenue) AS lowest_customer_revenue
FROM customer_revenue;


/*=============================================================================
Question 5
Business Question:
Create a reusable CTE that calculates total revenue generated by each seller.
=============================================================================*/

WITH seller_revenue AS
(
    SELECT
        s.seller_id AS seller,
        SUM(oi.price) AS revenue
    FROM order_items oi
    JOIN sellers s
        ON oi.seller_id = s.seller_id
    GROUP BY seller
);


/*=============================================================================
Question 6
Business Question:
Identify sellers whose revenue exceeds the average seller revenue.
=============================================================================*/

WITH seller_revenue AS
(
    SELECT
        s.seller_id AS seller,
        SUM(oi.price) AS revenue
    FROM order_items oi
    JOIN sellers s
        ON oi.seller_id = s.seller_id
    GROUP BY seller
)

SELECT *
FROM seller_revenue
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM seller_revenue
)
ORDER BY revenue DESC;


/*=============================================================================
Question 7
Business Question:
Retrieve the top 10 highest-revenue sellers.
=============================================================================*/

WITH seller_revenue AS
(
    SELECT
        s.seller_id AS seller,
        SUM(oi.price) AS revenue
    FROM order_items oi
    JOIN sellers s
        ON oi.seller_id = s.seller_id
    GROUP BY seller
)

SELECT *
FROM seller_revenue
ORDER BY revenue DESC
LIMIT 10;


/*=============================================================================
Question 8
Business Question:
Create a reusable CTE that calculates total revenue generated by each
product category.
=============================================================================*/

WITH category_revenue AS
(
    SELECT
        p.product_category_name AS category,
        SUM(oi.price) AS revenue
    FROM order_items oi
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY category
);


/*=============================================================================
Question 9
Business Question:
Identify product categories whose revenue exceeds the average
category revenue.
=============================================================================*/

WITH category_revenue AS
(
    SELECT
        p.product_category_name AS category,
        SUM(oi.price) AS revenue
    FROM order_items oi
    JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY category
)

SELECT *
FROM category_revenue
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM category_revenue
)
ORDER BY revenue DESC;


/*=============================================================================
Question 10
Business Question:
Create a reusable CTE that calculates monthly revenue.
=============================================================================*/

WITH monthly_revenue AS
(
    SELECT
        DATE_TRUNC('month', o.order_purchase_timestamp) AS purchase_month,
        SUM(op.payment_value) AS revenue
    FROM order_payments op
    JOIN orders o
        ON op.order_id = o.order_id
    GROUP BY purchase_month
);


/*=============================================================================
Question 11
Business Question:
Identify months whose revenue exceeds the average monthly revenue.
=============================================================================*/

WITH monthly_revenue AS
(
    SELECT
        DATE_TRUNC('month', o.order_purchase_timestamp) AS purchase_month,
        SUM(op.payment_value) AS revenue
    FROM order_payments op
    JOIN orders o
        ON op.order_id = o.order_id
    GROUP BY purchase_month
)

SELECT *
FROM monthly_revenue
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM monthly_revenue
)
ORDER BY revenue DESC;


/*=============================================================================
Question 12
Business Question:
Summarise overall customer revenue statistics using the reusable CTE.
=============================================================================*/

WITH customer_revenue AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS revenue
    FROM order_payments op
    JOIN orders o
        ON op.order_id = o.order_id
    JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY customer
)

SELECT
    COUNT(customer) AS total_customers,
    ROUND(SUM(revenue), 2) AS total_revenue,
    ROUND(AVG(revenue), 2) AS average_customer_revenue
FROM customer_revenue;


/*=============================================================================
Question 13
Business Question:
Demonstrate CTE chaining by creating a second CTE that filters
premium customers from the first CTE.
=============================================================================*/

WITH customer_revenue AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS revenue
    FROM order_payments op
    JOIN orders o
        ON op.order_id = o.order_id
    JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY customer
),

premium_customers AS
(
    SELECT *
    FROM customer_revenue
    WHERE revenue >
    (
        SELECT AVG(revenue)
        FROM customer_revenue
    )
)

SELECT *
FROM premium_customers
ORDER BY revenue DESC;


/*=============================================================================
Question 14
Business Question:
Explain why Common Table Expressions are often preferred over
nested subqueries in analytical SQL.
=============================================================================*/

-- Analyst Observation:
-- Common Table Expressions improve SQL readability by separating
-- complex logic into logical, reusable building blocks.
--
-- Benefits include:
-- • Reduced code duplication.
-- • Easier debugging.
-- • Improved maintainability.
-- • Simplified collaboration.
-- • Better readability for complex analytical queries.


/*=============================================================================
Question 15
Business Question:
Provide business recommendations based on the investigation.
=============================================================================*/

-- Business Recommendations

-- 1. Standardise analytical reporting using reusable CTEs for
--    customer, seller, product, and revenue summaries.

-- 2. Encourage analysts to replace repeated nested subqueries
--    with descriptive CTEs to improve maintainability.

-- 3. Adopt meaningful CTE naming conventions
--    (customer_revenue, monthly_revenue, category_revenue, etc.)
--    to improve readability across the analytics team.

-- 4. Build complex business reports by chaining multiple CTEs
--    instead of embedding deeply nested subqueries.

-- 5. Prepare these reusable CTE patterns for future conversion
--    into SQL Views to support dashboards and recurring reports.


/*=============================================================================
INVESTIGATION SUMMARY
===============================================================================

Key SQL Concepts Demonstrated
-----------------------------
✓ Common Table Expressions (CTEs)
✓ Reusable query logic
✓ Aggregate analysis
✓ Nested subqueries within CTEs
✓ Multiple (chained) CTEs
✓ Business summary tables
✓ SQL readability and maintainability
✓ Revenue analysis
✓ PostgreSQL WITH clause

Business Insights
-----------------
• Customer revenue can be calculated once and reused across
  multiple analytical reports.

• Seller performance analysis becomes significantly cleaner
  when intermediate revenue summaries are stored in CTEs.

• Product category and monthly revenue analyses benefit from
  reusable datasets, reducing duplicated SQL logic.

• Chained CTEs provide a scalable approach for building
  increasingly sophisticated business reports.

Analyst Reflection
------------------
This investigation marks the transition from writing functional SQL
to writing maintainable SQL.

By introducing Common Table Expressions, analytical workflows become
more modular, readable, and easier to extend. The use of chained CTEs
demonstrates how complex business logic can be broken into logical
steps, closely mirroring professional SQL development practices used
in production analytics environments.

===============================================================================
End of Investigation 24
===============================================================================