/*
===============================================================================
Investigation 25: SQL Views for Business Reporting
File: 20_sql_views_business_reporting.sql

Project:
Retail SQL Business Analysis (Brazilian E-Commerce Dataset)

Phase:
Phase 6 – Subqueries, Common Table Expressions (CTEs), and Views

Investigation:
25 – SQL Views for Business Reporting

Author:
Atsali Akolo

Database:
PostgreSQL

===============================================================================

BUSINESS OBJECTIVE
------------------
This investigation introduces SQL Views as persistent database objects that
store reusable SQL queries. Unlike Common Table Expressions (CTEs), Views
remain stored in the database and can be queried repeatedly without rewriting
complex joins and aggregations.

The investigation demonstrates how Views simplify business reporting by
encapsulating commonly used analytical queries such as customer revenue,
seller revenue, category revenue, and monthly revenue.

-------------------------------------------------------------------------------

LEARNING OBJECTIVES
-------------------
• Understand the purpose of SQL Views.
• Create reusable Views using CREATE VIEW.
• Query Views as if they were regular database tables.
• Compare Views with Subqueries and CTEs.
• Design reusable business reporting objects.
• Prepare datasets suitable for Business Intelligence dashboards.

-------------------------------------------------------------------------------

VIEW CREATION STRATEGY
----------------------

During development, CREATE OR REPLACE VIEW is used to safely update existing
Views without manually dropping them.

Example:

CREATE OR REPLACE VIEW customer_revenue_view AS
...

In production environments, Views are typically created once during database
deployment and reused indefinitely.

-------------------------------------------------------------------------------

RELATIONSHIP PATHS
------------------

Customer Revenue

customers
    ↓
orders
    ↓
order_payments

Seller Revenue

sellers
    ↓
order_items

Category Revenue

products
    ↓
order_items

Monthly Revenue

orders
    ↓
order_payments

===============================================================================
*/


/*=============================================================================
SECTION 1 — VIEW CREATION
=============================================================================*/


/*-----------------------------------------------------------------------------
Question 1
Business Question:
Create a View that calculates total revenue generated by each customer.
-----------------------------------------------------------------------------*/

CREATE OR REPLACE VIEW customer_revenue_view AS
SELECT
    c.customer_unique_id AS customer,
    SUM(op.payment_value) AS revenue
FROM order_payments op
JOIN orders o
    ON op.order_id = o.order_id
JOIN customers c
    ON o.customer_id = c.customer_id
GROUP BY customer;


/*-----------------------------------------------------------------------------
Question 2
Business Question:
Retrieve all customer revenue records using the View.
-----------------------------------------------------------------------------*/

SELECT *
FROM customer_revenue_view;


/*-----------------------------------------------------------------------------
Question 3
Business Question:
Identify customers whose revenue exceeds the average customer revenue.
-----------------------------------------------------------------------------*/

SELECT *
FROM customer_revenue_view
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM customer_revenue_view
)
ORDER BY revenue DESC;


/*-----------------------------------------------------------------------------
Question 4
Business Question:
Display the Top 10 highest-spending customers.
-----------------------------------------------------------------------------*/

SELECT *
FROM customer_revenue_view
ORDER BY revenue DESC
LIMIT 10;


/*-----------------------------------------------------------------------------
Question 5
Business Question:
Create a View that summarises seller revenue.
-----------------------------------------------------------------------------*/

CREATE OR REPLACE VIEW seller_revenue_view AS
SELECT
    s.seller_id AS seller,
    SUM(oi.price) AS revenue
FROM order_items oi
JOIN sellers s
    ON oi.seller_id = s.seller_id
GROUP BY seller;


/*-----------------------------------------------------------------------------
Question 6
Business Question:
Retrieve all seller revenue records.
-----------------------------------------------------------------------------*/

SELECT *
FROM seller_revenue_view;


/*-----------------------------------------------------------------------------
Question 7
Business Question:
Identify sellers whose revenue exceeds the average seller revenue.
-----------------------------------------------------------------------------*/

SELECT *
FROM seller_revenue_view
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM seller_revenue_view
)
ORDER BY revenue DESC;


/*-----------------------------------------------------------------------------
Question 8
Business Question:
Display the Top 10 highest-revenue sellers.
-----------------------------------------------------------------------------*/

SELECT *
FROM seller_revenue_view
ORDER BY revenue DESC
LIMIT 10;


/*=============================================================================
SECTION 2 — CATEGORY AND MONTHLY REPORTING VIEWS
=============================================================================*/


/*-----------------------------------------------------------------------------
Question 9
Business Question:
Create a View that summarises total revenue generated by each product category.
-----------------------------------------------------------------------------*/

CREATE OR REPLACE VIEW category_revenue_view AS
SELECT
    p.product_category_name AS category,
    SUM(oi.price) AS revenue
FROM order_items oi
JOIN products p
    ON oi.product_id = p.product_id
GROUP BY category;


/*-----------------------------------------------------------------------------
Question 10
Business Question:
Identify product categories whose revenue is above the average category revenue.
-----------------------------------------------------------------------------*/

SELECT *
FROM category_revenue_view
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM category_revenue_view
)
ORDER BY revenue DESC;


/*-----------------------------------------------------------------------------
Question 11
Business Question:
Create a View that summarises monthly sales revenue.
-----------------------------------------------------------------------------*/

CREATE OR REPLACE VIEW monthly_revenue_view AS
SELECT
    DATE_TRUNC('month', o.order_purchase_timestamp) AS purchase_month,
    SUM(op.payment_value) AS revenue
FROM order_payments op
JOIN orders o
    ON op.order_id = o.order_id
GROUP BY purchase_month;


/*-----------------------------------------------------------------------------
Question 12
Business Question:
Identify months whose revenue exceeded the average monthly revenue.
-----------------------------------------------------------------------------*/

SELECT *
FROM monthly_revenue_view
WHERE revenue >
(
    SELECT AVG(revenue)
    FROM monthly_revenue_view
)
ORDER BY purchase_month;


/*=============================================================================
SECTION 3 — ANALYST OBSERVATIONS
=============================================================================*/

/*
Question 13
Business Interpretation

Views significantly simplify recurring business analysis.

Instead of rewriting lengthy JOINs and aggregation queries,
analysts can query a View exactly as they would query a table.

Advantages observed:

• Cleaner SQL
• Less duplicated code
• Easier maintenance
• Consistent reporting logic
• Faster dashboard development
• Improved collaboration across analysts
*/


/*
Question 14
CTEs vs Views

Common Table Expressions (CTEs)

• Exist only for the duration of a single query.
• Created using the WITH keyword.
• Excellent for breaking complex queries into readable steps.
• Cannot be reused after the query completes.

Views

• Persist as database objects.
• Created once using CREATE VIEW (or CREATE OR REPLACE VIEW).
• Can be queried repeatedly by multiple users.
• Ideal for reusable business reports and BI dashboards.

Development Note

During development, CREATE OR REPLACE VIEW is the preferred approach because
it updates an existing View without requiring it to be dropped manually.

Alternative approaches include:

DROP VIEW IF EXISTS view_name;
CREATE VIEW view_name AS ...

This is useful when changing the View structure in ways that
CREATE OR REPLACE VIEW cannot accommodate.

For production systems:

• CREATE VIEW is typically executed once during deployment.
• Analysts then query the View directly without recreating it.
*/


/*
Question 15
Business Recommendations

The following Views would provide immediate value if exposed to reporting teams
or connected to Business Intelligence tools:

• customer_revenue_view
  - Supports customer segmentation and lifetime value analysis.

• seller_revenue_view
  - Enables seller performance monitoring and incentive programmes.

• category_revenue_view
  - Helps merchandising teams identify high-performing product categories.

• monthly_revenue_view
  - Supports executive reporting, trend analysis, forecasting,
    and dashboard visualisations.

These reusable Views establish a semantic reporting layer, reducing duplicated
business logic and ensuring consistent metrics across analyses.
*/


/*=============================================================================
SECTION 4 — KEY LEARNINGS
=============================================================================*/

/*
Technical Skills Demonstrated

✓ CREATE VIEW
✓ CREATE OR REPLACE VIEW
✓ Querying Views
✓ Aggregate Functions
✓ GROUP BY
✓ Reusable SQL Components
✓ Business Reporting Design
✓ Comparison of Views and CTEs
✓ Multi-table JOINs
✓ Nested Subqueries with Views

Business Skills Demonstrated

✓ Revenue Analysis
✓ Customer Analytics
✓ Seller Performance Analysis
✓ Product Category Analysis
✓ Time-Series Reporting
✓ Business Intelligence Preparation
✓ Reusable Reporting Architecture
*/


/*=============================================================================
SECTION 5 — INVESTIGATION SUMMARY
=============================================================================*/

/*
This investigation introduced SQL Views as reusable database objects for
business reporting.

By encapsulating complex JOIN and aggregation logic into persistent Views,
common analytical tasks become significantly simpler, more readable, and more
maintainable.

Unlike subqueries and CTEs, Views provide a reusable reporting layer that can
be shared across analysts, applications, and dashboards.

This approach mirrors real-world data warehouse and Business Intelligence
environments, where Views are frequently used to standardise business metrics,
simplify reporting workflows, and provide trusted datasets for downstream
analysis.
*/

-- ============================================================================
-- End of Investigation 25
-- File: 19_sql_views_business_reporting.sql
-- Phase 6 – Subqueries, Common Table Expressions (CTEs), and Views
-- ============================================================================