/*
===============================================================================
SQL Portfolio Project: Retail SQL Business Analysis
Phase 8: Advanced Business Analytics

Investigation 34: Customer Lifetime Value (CLV)

SQL Script: 28_customer_lifetime_value_analysis.sql

Database:
Brazilian E-Commerce Public Dataset (Olist)

Author:
Atsali Akolo

SQL Dialect:
PostgreSQL

Analytical Framework
--------------------
Population:
    Customers with at least one delivered order.

Grain:
    One row per customer_unique_id.

Revenue:
    SUM(order_payments.payment_value) for delivered orders.

Normalization:
    PERCENT_RANK() * 100

Base Customer Value Score:
    Revenue       40%
    Frequency     25%
    AOV           20%
    Lifespan      15%

Customer Value Tiers:
    VIP          >= 90
    High Value   >= 75
    Growth       >= 60
    Standard     >= 40
    Low Value    < 40

Business Objective:
Develop a historical customer-value framework that combines realised
revenue, purchasing frequency, average order value and purchasing lifespan
into a normalized and weighted Customer Value Score.

Important Scope Note:
This is a historical realised-value model, not a predictive CLV model.
It does not forecast future customer revenue, churn probability or future
customer lifespan.
===============================================================================
*/


/*==============================================================================
Question 1
Define and validate the analytical customer population.
==============================================================================*/

WITH population AS
(
    SELECT
        c.customer_unique_id AS customer,
        COUNT(DISTINCT o.order_id) AS delivered_orders,
        MIN(o.order_purchase_timestamp) AS first_purchase_date,
        MAX(o.order_purchase_timestamp) AS latest_purchase_date

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
)

SELECT
    COUNT(*) AS analytical_customers,
    SUM(delivered_orders) AS delivered_orders,
    MIN(first_purchase_date) AS earliest_purchase,
    MAX(latest_purchase_date) AS latest_purchase

FROM population;


/*==============================================================================
Question 2
Calculate historical lifetime revenue generated by every customer.
==============================================================================*/

SELECT
    c.customer_unique_id AS customer,
    SUM(op.payment_value) AS lifetime_revenue

FROM customers c

JOIN orders o
    ON o.customer_id = c.customer_id

JOIN order_payments op
    ON op.order_id = o.order_id

WHERE o.order_status = 'delivered'

GROUP BY c.customer_unique_id

ORDER BY lifetime_revenue DESC;


/*==============================================================================
Question 3
Calculate purchase frequency and Average Order Value (AOV).
==============================================================================*/

WITH customer_metrics AS
(
    SELECT
        c.customer_unique_id AS customer,
        COUNT(DISTINCT o.order_id) AS order_frequency,
        SUM(op.payment_value) AS lifetime_revenue

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    JOIN order_payments op
        ON op.order_id = o.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
)

SELECT
    customer,
    order_frequency,

    ROUND(
        (
            lifetime_revenue
            /
            NULLIF(order_frequency, 0)
        )::numeric,
        2
    ) AS avg_order_value,

    ROUND(lifetime_revenue::numeric, 2) AS lifetime_revenue

FROM customer_metrics

ORDER BY lifetime_revenue DESC;


/*==============================================================================
Question 4
Determine each customer's first delivered purchase date.
==============================================================================*/

SELECT
    c.customer_unique_id AS customer,
    MIN(o.order_purchase_timestamp) AS first_purchase_date

FROM customers c

JOIN orders o
    ON o.customer_id = c.customer_id

WHERE o.order_status = 'delivered'

GROUP BY c.customer_unique_id;


/*==============================================================================
Question 5
Determine each customer's most recent delivered purchase date.
==============================================================================*/

SELECT
    c.customer_unique_id AS customer,
    MAX(o.order_purchase_timestamp) AS latest_purchase_date

FROM customers c

JOIN orders o
    ON o.customer_id = c.customer_id

WHERE o.order_status = 'delivered'

GROUP BY c.customer_unique_id;


/*==============================================================================
Question 6
Calculate purchasing lifespan for every customer.
==============================================================================*/

WITH purchase_history AS
(
    SELECT
        c.customer_unique_id AS customer,
        MIN(o.order_purchase_timestamp) AS first_purchase_date,
        MAX(o.order_purchase_timestamp) AS latest_purchase_date

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
)

SELECT
    customer,
    first_purchase_date,
    latest_purchase_date,

    ROUND(
        (
            EXTRACT(
                EPOCH FROM
                (
                    latest_purchase_date
                    -
                    first_purchase_date
                )
            )
            /
            86400.0
        )::numeric,
        2
    ) AS purchasing_lifespan_days

FROM purchase_history;


/*==============================================================================
Question 7
Profile the distribution of lifetime revenue across customers.
==============================================================================*/

WITH customer_revenue AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS lifetime_revenue

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    JOIN order_payments op
        ON op.order_id = o.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
)

SELECT
    COUNT(*) AS customers,
    ROUND(MIN(lifetime_revenue)::numeric, 2) AS minimum_revenue,
    ROUND(MAX(lifetime_revenue)::numeric, 2) AS maximum_revenue,
    ROUND(AVG(lifetime_revenue)::numeric, 2) AS average_revenue,

    ROUND(
        PERCENTILE_CONT(0.25)
        WITHIN GROUP (ORDER BY lifetime_revenue)::numeric,
        2
    ) AS q1_revenue,

    ROUND(
        PERCENTILE_CONT(0.50)
        WITHIN GROUP (ORDER BY lifetime_revenue)::numeric,
        2
    ) AS median_revenue,

    ROUND(
        PERCENTILE_CONT(0.75)
        WITHIN GROUP (ORDER BY lifetime_revenue)::numeric,
        2
    ) AS q3_revenue,

    ROUND(
        PERCENTILE_CONT(0.90)
        WITHIN GROUP (ORDER BY lifetime_revenue)::numeric,
        2
    ) AS p90_revenue,

    ROUND(
        PERCENTILE_CONT(0.95)
        WITHIN GROUP (ORDER BY lifetime_revenue)::numeric,
        2
    ) AS p95_revenue

FROM customer_revenue;


/*==============================================================================
Question 8
Profile the distributions of purchase frequency and AOV.
==============================================================================*/

WITH customer_metrics AS
(
    SELECT
        c.customer_unique_id AS customer,
        COUNT(DISTINCT o.order_id) AS order_frequency,

        SUM(op.payment_value)
        /
        NULLIF(COUNT(DISTINCT o.order_id), 0) AS aov

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    JOIN order_payments op
        ON op.order_id = o.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
)

SELECT
    COUNT(*) AS customers,

    MIN(order_frequency) AS frequency_min,
    MAX(order_frequency) AS frequency_max,
    ROUND(AVG(order_frequency)::numeric, 2) AS frequency_avg,

    ROUND(
        PERCENTILE_CONT(0.50)
        WITHIN GROUP (ORDER BY order_frequency)::numeric,
        2
    ) AS frequency_median,

    ROUND(
        PERCENTILE_CONT(0.75)
        WITHIN GROUP (ORDER BY order_frequency)::numeric,
        2
    ) AS frequency_q3,

    ROUND(MIN(aov)::numeric, 2) AS aov_min,
    ROUND(MAX(aov)::numeric, 2) AS aov_max,
    ROUND(AVG(aov)::numeric, 2) AS aov_avg,

    ROUND(
        PERCENTILE_CONT(0.50)
        WITHIN GROUP (ORDER BY aov)::numeric,
        2
    ) AS aov_median,

    ROUND(
        PERCENTILE_CONT(0.75)
        WITHIN GROUP (ORDER BY aov)::numeric,
        2
    ) AS aov_q3

FROM customer_metrics;


/*==============================================================================
Question 9
Profile purchasing lifespan and identify one-time customers.
==============================================================================*/

WITH purchase_history AS
(
    SELECT
        c.customer_unique_id AS customer,
        MIN(o.order_purchase_timestamp) AS first_purchase,
        MAX(o.order_purchase_timestamp) AS latest_purchase

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
),

customer_lifespan AS
(
    SELECT
        customer,

        EXTRACT(
            EPOCH FROM
            (
                latest_purchase
                -
                first_purchase
            )
        ) / 86400.0 AS lifespan_days

    FROM purchase_history
)

SELECT
    COUNT(*) AS customers,

    COUNT(*) FILTER (
        WHERE lifespan_days = 0
    ) AS one_time_customers,

    ROUND(
        (
            COUNT(*) FILTER (
                WHERE lifespan_days = 0
            )
            * 100.0
            /
            NULLIF(COUNT(*), 0)
        )::numeric,
        2
    ) AS one_time_percentage,

    ROUND(MIN(lifespan_days)::numeric, 2) AS minimum_lifespan,
    ROUND(MAX(lifespan_days)::numeric, 2) AS maximum_lifespan,
    ROUND(AVG(lifespan_days)::numeric, 2) AS average_lifespan,

    ROUND(
        PERCENTILE_CONT(0.50)
        WITHIN GROUP (ORDER BY lifespan_days)::numeric,
        2
    ) AS median_lifespan,

    ROUND(
        PERCENTILE_CONT(0.75)
        WITHIN GROUP (ORDER BY lifespan_days)::numeric,
        2
    ) AS q3_lifespan,

    ROUND(
        PERCENTILE_CONT(0.90)
        WITHIN GROUP (ORDER BY lifespan_days)::numeric,
        2
    ) AS p90_lifespan

FROM customer_lifespan;


/*==============================================================================
Question 10
Normalize the four customer-value metrics to a 0-100 scale using
PERCENT_RANK().

Higher values are treated as stronger customer-value characteristics.
Ties are intentionally preserved by PERCENT_RANK().
==============================================================================*/

WITH customer_metrics AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS lifetime_revenue,
        COUNT(DISTINCT o.order_id) AS order_frequency,

        SUM(op.payment_value)
        /
        NULLIF(COUNT(DISTINCT o.order_id), 0) AS aov,

        EXTRACT(
            EPOCH FROM
            (
                MAX(o.order_purchase_timestamp)
                -
                MIN(o.order_purchase_timestamp)
            )
        ) / 86400.0 AS lifespan_days

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    JOIN order_payments op
        ON op.order_id = o.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
)

SELECT
    customer,
    ROUND(lifetime_revenue::numeric, 2) AS lifetime_revenue,
    order_frequency,
    ROUND(aov::numeric, 2) AS aov,
    ROUND(lifespan_days::numeric, 2) AS lifespan_days,

    ROUND(
        (
            PERCENT_RANK()
            OVER (ORDER BY lifetime_revenue)
            * 100
        )::numeric,
        2
    ) AS revenue_score,

    ROUND(
        (
            PERCENT_RANK()
            OVER (ORDER BY order_frequency)
            * 100
        )::numeric,
        2
    ) AS frequency_score,

    ROUND(
        (
            PERCENT_RANK()
            OVER (ORDER BY aov)
            * 100
        )::numeric,
        2
    ) AS aov_score,

    ROUND(
        (
            PERCENT_RANK()
            OVER (ORDER BY lifespan_days)
            * 100
        )::numeric,
        2
    ) AS lifespan_score

FROM customer_metrics;


/*==============================================================================
Question 11
Calculate the base weighted Customer Value Score.

Weights:
    Revenue   = 40%
    Frequency = 25%
    AOV       = 20%
    Lifespan  = 15%
==============================================================================*/

WITH customer_metrics AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS lifetime_revenue,
        COUNT(DISTINCT o.order_id) AS frequency,

        SUM(op.payment_value)
        /
        NULLIF(COUNT(DISTINCT o.order_id), 0) AS aov,

        EXTRACT(
            EPOCH FROM
            (
                MAX(o.order_purchase_timestamp)
                -
                MIN(o.order_purchase_timestamp)
            )
        ) / 86400.0 AS lifespan

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    JOIN order_payments op
        ON op.order_id = o.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
),

normalized AS
(
    SELECT
        *,

        PERCENT_RANK()
        OVER (ORDER BY lifetime_revenue) * 100 AS revenue_score,

        PERCENT_RANK()
        OVER (ORDER BY frequency) * 100 AS frequency_score,

        PERCENT_RANK()
        OVER (ORDER BY aov) * 100 AS aov_score,

        PERCENT_RANK()
        OVER (ORDER BY lifespan) * 100 AS lifespan_score

    FROM customer_metrics
)

SELECT
    customer,
    ROUND(lifetime_revenue::numeric, 2) AS lifetime_revenue,
    frequency,
    ROUND(aov::numeric, 2) AS aov,
    ROUND(lifespan::numeric, 2) AS lifespan_days,

    ROUND(revenue_score::numeric, 2) AS revenue_score,
    ROUND(frequency_score::numeric, 2) AS frequency_score,
    ROUND(aov_score::numeric, 2) AS aov_score,
    ROUND(lifespan_score::numeric, 2) AS lifespan_score,

    ROUND(
        (
            revenue_score * 0.40
            +
            frequency_score * 0.25
            +
            aov_score * 0.20
            +
            lifespan_score * 0.15
        )::numeric,
        2
    ) AS customer_value_score

FROM normalized

ORDER BY customer_value_score DESC;


/*==============================================================================
Question 12
Test alternative weighting models.

Economic Model:
    Revenue 50%, Frequency 20%, AOV 20%, Lifespan 10%

Relationship Model:
    Revenue 30%, Frequency 30%, AOV 15%, Lifespan 25%

Balanced Model:
    Revenue 40%, Frequency 25%, AOV 20%, Lifespan 15%
==============================================================================*/

WITH customer_metrics AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS revenue,
        COUNT(DISTINCT o.order_id) AS frequency,

        SUM(op.payment_value)
        /
        NULLIF(COUNT(DISTINCT o.order_id), 0) AS aov,

        EXTRACT(
            EPOCH FROM
            (
                MAX(o.order_purchase_timestamp)
                -
                MIN(o.order_purchase_timestamp)
            )
        ) / 86400.0 AS lifespan

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    JOIN order_payments op
        ON op.order_id = o.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
),

normalized AS
(
    SELECT
        *,

        PERCENT_RANK()
        OVER (ORDER BY revenue) * 100 AS revenue_score,

        PERCENT_RANK()
        OVER (ORDER BY frequency) * 100 AS frequency_score,

        PERCENT_RANK()
        OVER (ORDER BY aov) * 100 AS aov_score,

        PERCENT_RANK()
        OVER (ORDER BY lifespan) * 100 AS lifespan_score

    FROM customer_metrics
),

scores AS
(
    SELECT
        *,

        revenue_score * 0.50
        + frequency_score * 0.20
        + aov_score * 0.20
        + lifespan_score * 0.10
            AS economic_score,

        revenue_score * 0.30
        + frequency_score * 0.30
        + aov_score * 0.15
        + lifespan_score * 0.25
            AS relationship_score,

        revenue_score * 0.40
        + frequency_score * 0.25
        + aov_score * 0.20
        + lifespan_score * 0.15
            AS balanced_score

    FROM normalized
)

SELECT
    customer,

    ROUND(economic_score::numeric, 2) AS economic_score,
    ROUND(relationship_score::numeric, 2) AS relationship_score,
    ROUND(balanced_score::numeric, 2) AS balanced_score,

    CASE
        WHEN economic_score >= 90 THEN 'VIP'
        WHEN economic_score >= 75 THEN 'High Value'
        WHEN economic_score >= 60 THEN 'Growth'
        WHEN economic_score >= 40 THEN 'Standard'
        ELSE 'Low Value'
    END AS economic_tier,

    CASE
        WHEN relationship_score >= 90 THEN 'VIP'
        WHEN relationship_score >= 75 THEN 'High Value'
        WHEN relationship_score >= 60 THEN 'Growth'
        WHEN relationship_score >= 40 THEN 'Standard'
        ELSE 'Low Value'
    END AS relationship_tier,

    CASE
        WHEN balanced_score >= 90 THEN 'VIP'
        WHEN balanced_score >= 75 THEN 'High Value'
        WHEN balanced_score >= 60 THEN 'Growth'
        WHEN balanced_score >= 40 THEN 'Standard'
        ELSE 'Low Value'
    END AS balanced_tier

FROM scores

ORDER BY balanced_score DESC;


/*==============================================================================
Question 13
Classify customers using the base Customer Value Score.
==============================================================================*/

WITH customer_metrics AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS revenue,
        COUNT(DISTINCT o.order_id) AS frequency,

        SUM(op.payment_value)
        /
        NULLIF(COUNT(DISTINCT o.order_id), 0) AS aov,

        EXTRACT(
            EPOCH FROM
            (
                MAX(o.order_purchase_timestamp)
                -
                MIN(o.order_purchase_timestamp)
            )
        ) / 86400.0 AS lifespan

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    JOIN order_payments op
        ON op.order_id = o.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
),

scored AS
(
    SELECT
        *,

        PERCENT_RANK()
        OVER (ORDER BY revenue) * 100 AS revenue_score,

        PERCENT_RANK()
        OVER (ORDER BY frequency) * 100 AS frequency_score,

        PERCENT_RANK()
        OVER (ORDER BY aov) * 100 AS aov_score,

        PERCENT_RANK()
        OVER (ORDER BY lifespan) * 100 AS lifespan_score

    FROM customer_metrics
),

customer_value AS
(
    SELECT
        *,

        revenue_score * 0.40
        + frequency_score * 0.25
        + aov_score * 0.20
        + lifespan_score * 0.15
            AS customer_value_score

    FROM scored
)

SELECT
    customer,
    ROUND(revenue::numeric, 2) AS lifetime_revenue,
    frequency,
    ROUND(aov::numeric, 2) AS aov,
    ROUND(lifespan::numeric, 2) AS lifespan_days,

    ROUND(customer_value_score::numeric, 2)
        AS customer_value_score,

    CASE
        WHEN customer_value_score >= 90 THEN 'VIP'
        WHEN customer_value_score >= 75 THEN 'High Value'
        WHEN customer_value_score >= 60 THEN 'Growth'
        WHEN customer_value_score >= 40 THEN 'Standard'
        ELSE 'Low Value'
    END AS customer_value_tier

FROM customer_value

ORDER BY customer_value_score DESC;


/*==============================================================================
Question 14
Validate the characteristics and revenue contribution of each customer tier.
==============================================================================*/

WITH customer_metrics AS
(
    SELECT
        c.customer_unique_id AS customer,
        SUM(op.payment_value) AS revenue,
        COUNT(DISTINCT o.order_id) AS frequency,

        SUM(op.payment_value)
        /
        NULLIF(COUNT(DISTINCT o.order_id), 0) AS aov,

        EXTRACT(
            EPOCH FROM
            (
                MAX(o.order_purchase_timestamp)
                -
                MIN(o.order_purchase_timestamp)
            )
        ) / 86400.0 AS lifespan

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    JOIN order_payments op
        ON op.order_id = o.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
),

normalized AS
(
    SELECT
        *,

        PERCENT_RANK()
        OVER (ORDER BY revenue) * 100 AS revenue_score,

        PERCENT_RANK()
        OVER (ORDER BY frequency) * 100 AS frequency_score,

        PERCENT_RANK()
        OVER (ORDER BY aov) * 100 AS aov_score,

        PERCENT_RANK()
        OVER (ORDER BY lifespan) * 100 AS lifespan_score

    FROM customer_metrics
),

scored AS
(
    SELECT
        *,

        revenue_score * 0.40
        + frequency_score * 0.25
        + aov_score * 0.20
        + lifespan_score * 0.15
            AS score

    FROM normalized
),

classified AS
(
    SELECT
        *,

        CASE
            WHEN score >= 90 THEN 'VIP'
            WHEN score >= 75 THEN 'High Value'
            WHEN score >= 60 THEN 'Growth'
            WHEN score >= 40 THEN 'Standard'
            ELSE 'Low Value'
        END AS tier

    FROM scored
)

SELECT
    tier AS customer_value_tier,
    COUNT(*) AS customers,

    ROUND(
        (
            COUNT(*) * 100.0
            /
            SUM(COUNT(*)) OVER ()
        )::numeric,
        2
    ) AS customer_percentage,

    ROUND(SUM(revenue)::numeric, 2) AS total_revenue,

    ROUND(
        (
            SUM(revenue) * 100.0
            /
            SUM(SUM(revenue)) OVER ()
        )::numeric,
        2
    ) AS revenue_percentage,

    ROUND(AVG(revenue)::numeric, 2) AS average_revenue,
    ROUND(AVG(frequency)::numeric, 2) AS average_frequency,
    ROUND(AVG(aov)::numeric, 2) AS average_aov,
    ROUND(AVG(lifespan)::numeric, 2) AS average_lifespan,
    ROUND(AVG(score)::numeric, 2) AS average_score

FROM classified

GROUP BY tier

ORDER BY
    CASE tier
        WHEN 'VIP' THEN 1
        WHEN 'High Value' THEN 2
        WHEN 'Growth' THEN 3
        WHEN 'Standard' THEN 4
        ELSE 5
    END;


/*==============================================================================
Question 15
Build the final reusable Customer Value Dashboard.

The view is the authoritative analytical output for Investigation 34.
==============================================================================*/

DROP VIEW IF EXISTS customer_value_dashboard;

CREATE VIEW customer_value_dashboard AS

WITH base AS
(
    SELECT
        c.customer_unique_id AS customer,

        SUM(op.payment_value) AS lifetime_revenue,

        COUNT(DISTINCT o.order_id) AS order_frequency,

        SUM(op.payment_value)
        /
        NULLIF(COUNT(DISTINCT o.order_id), 0)
            AS avg_order_value,

        MIN(o.order_purchase_timestamp)
            AS first_purchase_date,

        MAX(o.order_purchase_timestamp)
            AS latest_purchase_date,

        EXTRACT(
            EPOCH FROM
            (
                MAX(o.order_purchase_timestamp)
                -
                MIN(o.order_purchase_timestamp)
            )
        ) / 86400.0
            AS purchasing_lifespan_days

    FROM customers c

    JOIN orders o
        ON o.customer_id = c.customer_id

    JOIN order_payments op
        ON op.order_id = o.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
),

normalized AS
(
    SELECT
        *,

        PERCENT_RANK()
        OVER (ORDER BY lifetime_revenue) * 100
            AS revenue_score,

        PERCENT_RANK()
        OVER (ORDER BY order_frequency) * 100
            AS frequency_score,

        PERCENT_RANK()
        OVER (ORDER BY avg_order_value) * 100
            AS aov_score,

        PERCENT_RANK()
        OVER (ORDER BY purchasing_lifespan_days) * 100
            AS lifespan_score

    FROM base
),

scored AS
(
    SELECT
        *,

        revenue_score * 0.40
        + frequency_score * 0.25
        + aov_score * 0.20
        + lifespan_score * 0.15
            AS customer_value_score,

        revenue_score * 0.50
        + frequency_score * 0.20
        + aov_score * 0.20
        + lifespan_score * 0.10
            AS economic_contribution_score,

        revenue_score * 0.30
        + frequency_score * 0.30
        + aov_score * 0.15
        + lifespan_score * 0.25
            AS relationship_oriented_score

    FROM normalized
),

ranked AS
(
    SELECT
        *,

        RANK()
        OVER (
            ORDER BY lifetime_revenue DESC
        ) AS revenue_rank,

        RANK()
        OVER (
            ORDER BY customer_value_score DESC
        ) AS customer_value_rank

    FROM scored
)

SELECT
    customer,

    ROUND(lifetime_revenue::numeric, 2)
        AS lifetime_revenue,

    order_frequency,

    ROUND(avg_order_value::numeric, 2)
        AS avg_order_value,

    first_purchase_date,
    latest_purchase_date,

    ROUND(purchasing_lifespan_days::numeric, 2)
        AS purchasing_lifespan_days,

    ROUND(revenue_score::numeric, 2)
        AS revenue_score,

    ROUND(frequency_score::numeric, 2)
        AS frequency_score,

    ROUND(aov_score::numeric, 2)
        AS aov_score,

    ROUND(lifespan_score::numeric, 2)
        AS lifespan_score,

    ROUND(customer_value_score::numeric, 2)
        AS customer_value_score,

    CASE
        WHEN customer_value_score >= 90 THEN 'VIP'
        WHEN customer_value_score >= 75 THEN 'High Value'
        WHEN customer_value_score >= 60 THEN 'Growth'
        WHEN customer_value_score >= 40 THEN 'Standard'
        ELSE 'Low Value'
    END AS customer_value_tier,

    revenue_rank,
    customer_value_rank,

    ROUND(economic_contribution_score::numeric, 2)
        AS economic_contribution_score,

    ROUND(relationship_oriented_score::numeric, 2)
        AS relationship_oriented_score

FROM ranked;
