/*
===============================================================================
 Retail SQL Business Analysis
 Investigation 37 – Product Portfolio Analysis
 SQL File: 31_product_portfolio_analysis.sql

 Phase 8 – Strategic Business Analytics

 Author: Atsali Akolo
 Database: PostgreSQL
 Dataset: Brazilian E-Commerce Public Dataset (Olist)

-----------------------------------------------------------------------------
 BUSINESS OBJECTIVE
-----------------------------------------------------------------------------
 Develop a comprehensive Product Portfolio Scorecard by evaluating products
 across multiple business dimensions rather than relying solely on sales
 volume.

 This investigation measures:

 • Product Revenue
 • Units Sold
 • Customer Satisfaction
 • Freight Efficiency
 • Category Performance

 These KPIs will later be standardized into a weighted Product Performance
 Score suitable for executive dashboards and strategic decision-making.
===============================================================================
*/

-- ============================================================================
-- QUESTION 1
-- Calculate the total revenue generated by each product.
-- Revenue is calculated using the product selling price
-- (order_items.price) rather than payment value.
-- ============================================================================

WITH product_revenue AS
(
    SELECT
        product_id AS product,
        SUM(price) AS total_revenue
    FROM order_items
    GROUP BY product
)

SELECT *
FROM product_revenue
ORDER BY total_revenue DESC;

-- ============================================================================
-- QUESTION 2
-- Calculate the total number of units sold for each product.
-- This measures overall customer demand.
-- ============================================================================

WITH product_sales AS
(
    SELECT
        product_id AS product,
        COUNT(product_id) AS units_sold
    FROM order_items
    GROUP BY product
)

SELECT *
FROM product_sales
ORDER BY units_sold DESC;

-- ============================================================================
-- QUESTION 3
-- Calculate the average customer review score for each product.
-- Higher review scores indicate greater customer satisfaction.
-- ============================================================================

WITH product_reviews AS
(
    SELECT
        oi.product_id AS product,
        ROUND(
            AVG(orv.review_score),
            2
        ) AS average_review_score
    FROM order_items oi

    JOIN order_reviews orv
        ON oi.order_id = orv.order_id

    GROUP BY product
)

SELECT *
FROM product_reviews
ORDER BY average_review_score DESC;

-- ============================================================================
-- QUESTION 4
-- Calculate the average freight cost for each product.
-- Freight cost will later be treated as a negative KPI, where lower
-- shipping costs contribute positively to the overall performance score.
-- ============================================================================

WITH product_freight AS
(
    SELECT
        product_id AS product,
        ROUND(
            AVG(freight_value),
            2
        ) AS average_freight_cost
    FROM order_items
    GROUP BY product
)

SELECT *
FROM product_freight
ORDER BY average_freight_cost ASC;

-- ============================================================================
-- QUESTION 5A
-- Retrieve the product category assigned to every product.
-- This mapping will be used later when calculating category-relative
-- performance scores.
-- ============================================================================

WITH product_categories AS
(
    SELECT
        product_id AS product,
        product_category_name AS category
    FROM products
)

SELECT *
FROM product_categories
ORDER BY category;

-- ============================================================================
-- QUESTION 5B
-- Calculate the total number of products available within each category.
-- This provides an overview of catalogue distribution across the marketplace.
-- ============================================================================

WITH category_product_counts AS
(
    SELECT
        product_category_name AS category,
        COUNT(DISTINCT product_id) AS total_products
    FROM products
    GROUP BY category
)

SELECT *
FROM category_product_counts
ORDER BY total_products DESC;

/*
===============================================================================
 END OF PART 1

 Part 1 established the foundational KPIs required for the Product Portfolio
 Scorecard:

 • Product Revenue
 • Units Sold
 • Average Review Score
 • Average Freight Cost
 • Product Categories
 • Product Counts by Category

 Part 2 builds upon these metrics by introducing revenue rankings, sales
 rankings, category revenue analysis, and category-relative performance
 scoring.
===============================================================================
*/

-- ============================================================================
-- Investigation 37 – Product Portfolio Analysis
-- SQL File: 31_product_portfolio_analysis.sql
-- Part 2 of 3
--
-- This section introduces product rankings and category-level analytics that
-- form the basis of the Product Performance Scorecard.
--
-- Key analytical concepts:
-- • Revenue Ranking
-- • Sales Ranking
-- • Customer Satisfaction Ranking
-- • Category Revenue Analysis
-- • Category Performance Scoring
-- ============================================================================


-- ============================================================================
-- QUESTION 6
-- Calculate the average revenue generated per sale for each product.
-- This metric measures the average selling value whenever a product is sold.
-- ============================================================================

WITH product_revenue AS
(
    SELECT
        product_id AS product,
        SUM(price) AS total_revenue
    FROM order_items
    GROUP BY product
),

product_sales AS
(
    SELECT
        product_id AS product,
        COUNT(*) AS units_sold
    FROM order_items
    GROUP BY product
),

average_revenue_per_sale AS
(
    SELECT
        pr.product,
        pr.total_revenue,
        ps.units_sold,

        ROUND(
            pr.total_revenue /
            ps.units_sold,
            2
        ) AS average_revenue_per_sale

    FROM product_revenue pr

    JOIN product_sales ps
        ON pr.product = ps.product
)

SELECT *
FROM average_revenue_per_sale
ORDER BY average_revenue_per_sale DESC;


-- ============================================================================
-- QUESTION 7
-- Rank products by total revenue.
-- Higher revenue receives a better ranking.
-- ============================================================================

WITH product_revenue AS
(
    SELECT
        product_id AS product,
        SUM(price) AS total_revenue

    FROM order_items

    GROUP BY product
)

SELECT

    product,

    total_revenue,

    RANK() OVER
    (
        ORDER BY total_revenue DESC
    ) AS revenue_rank

FROM product_revenue

ORDER BY revenue_rank;


-- ============================================================================
-- QUESTION 8
-- Rank products according to units sold.
-- ============================================================================

WITH product_sales AS
(
    SELECT

        product_id AS product,

        COUNT(*) AS units_sold

    FROM order_items

    GROUP BY product
)

SELECT

    product,

    units_sold,

    RANK() OVER
    (
        ORDER BY units_sold DESC
    ) AS sales_rank

FROM product_sales

ORDER BY sales_rank;


-- ============================================================================
-- QUESTION 9
-- Rank products according to customer review score.
--
-- Products with fewer than 30 reviews are excluded to reduce statistical
-- noise caused by very small sample sizes.
-- ============================================================================

WITH product_reviews AS
(
    SELECT

        oi.product_id AS product,

        COUNT(orv.review_score) AS review_count,

        ROUND(
            AVG(orv.review_score),
            2
        ) AS average_review_score

    FROM order_items oi

    JOIN order_reviews orv

        ON oi.order_id = orv.order_id

    GROUP BY product

    HAVING COUNT(orv.review_score) >= 30
)

SELECT

    product,

    review_count,

    average_review_score,

    RANK() OVER
    (
        ORDER BY average_review_score DESC
    ) AS review_rank

FROM product_reviews

ORDER BY review_rank;


-- ============================================================================
-- QUESTION 10
-- Calculate revenue generated by every product category.
--
-- This identifies which categories contribute the greatest share of company
-- revenue.
-- ============================================================================

WITH product_revenue AS
(
    SELECT

        product_id AS product,

        SUM(price) AS total_revenue

    FROM order_items

    GROUP BY product
),

product_categories AS
(
    SELECT

        product_id AS product,

        product_category_name AS category

    FROM products
),

category_revenue AS
(
    SELECT

        pc.category,

        SUM(pr.total_revenue) AS category_revenue

    FROM product_categories pc

    JOIN product_revenue pr

        ON pc.product = pr.product

    GROUP BY pc.category
)

SELECT *

FROM category_revenue

ORDER BY category_revenue DESC;


-- ============================================================================
-- CATEGORY PERFORMANCE SCORING
--
-- Products are evaluated against competitors within the SAME category.
--
-- Instead of rewarding products simply because they belong to a successful
-- category, each product is compared only with similar products.
--
-- NTILE(100) converts revenue into percentile scores ranging from 1–100.
--
-- ASCENDING ORDER:
--
-- Lowest revenue  → Lowest score
-- Highest revenue → Highest score
--
-- This category score will become one component of the final weighted
-- Product Performance Score.
-- ============================================================================

WITH category_performance AS
(
    SELECT

        p.product_id AS product,

        p.product_category_name AS category,

        SUM(oi.price) AS revenue,

        NTILE(100) OVER
        (
            PARTITION BY p.product_category_name
            ORDER BY SUM(oi.price) ASC
        ) AS category_score

    FROM products p

    JOIN order_items oi

        ON p.product_id = oi.product_id

    GROUP BY
        p.product_id,
        p.product_category_name
)

SELECT *

FROM category_performance

ORDER BY
    category,
    category_score DESC;


/*
===============================================================================
 END OF PART 2

 This section introduced analytical rankings used later to build the Product
 Performance Scorecard.

 Metrics completed:

 ✓ Average Revenue per Sale
 ✓ Revenue Ranking
 ✓ Sales Ranking
 ✓ Review Ranking
 ✓ Category Revenue Analysis
 ✓ Category Performance Score

 Part 3 combines all KPIs into a standardized weighted Product Performance
 Index, classifies every product, and generates executive-ready summary
 outputs suitable for Business Intelligence dashboards.

===============================================================================
*/

-- =============================================================================
-- Investigation 37 – Product Portfolio Analysis
-- SQL File: 31_product_portfolio_analysis.sql
-- Part 3 of 3
--
-- This section integrates all calculated KPIs into a unified Product
-- Performance Scorecard. Metrics are standardized to a common 1–100 scale,
-- weighted according to business importance, and combined into a Product
-- Performance Index for portfolio evaluation.
--
-- The resulting dataset can be directly consumed by Business Intelligence
-- dashboards and executive reporting tools.
-- =============================================================================


-- =============================================================================
-- QUESTION 11
-- Build a consolidated Product Summary containing all KPIs.
-- =============================================================================

WITH product_revenue AS
(
    SELECT
        product_id AS product,
        SUM(price) AS revenue
    FROM order_items
    GROUP BY product_id
),

product_sales AS
(
    SELECT
        product_id AS product,
        COUNT(*) AS units_sold
    FROM order_items
    GROUP BY product_id
),

product_reviews AS
(
    SELECT
        oi.product_id AS product,
        ROUND(AVG(orv.review_score),2) AS review_score
    FROM order_items oi
    JOIN order_reviews orv
        ON oi.order_id = orv.order_id
    GROUP BY oi.product_id
),

product_freight AS
(
    SELECT
        product_id AS product,
        ROUND(AVG(freight_value),2) AS average_freight_cost
    FROM order_items
    GROUP BY product_id
),

category_performance AS
(
    SELECT
        p.product_id AS product,

        NTILE(100) OVER
        (
            PARTITION BY p.product_category_name
            ORDER BY SUM(oi.price) ASC
        ) AS category_score

    FROM products p

    JOIN order_items oi
        ON p.product_id = oi.product_id

    GROUP BY
        p.product_id,
        p.product_category_name
)

SELECT

    pr.product,

    pr.revenue,

    ps.units_sold,

    prev.review_score,

    pf.average_freight_cost,

    cp.category_score

FROM product_revenue pr

JOIN product_sales ps
    ON pr.product = ps.product

JOIN product_reviews prev
    ON pr.product = prev.product

JOIN product_freight pf
    ON pr.product = pf.product

JOIN category_performance cp
    ON pr.product = cp.product

ORDER BY revenue DESC;



-- =============================================================================
-- QUESTION 12
-- Standardize KPIs into a common 1–100 scoring framework and calculate the
-- weighted Product Performance Score.
--
-- Weighting Model
--
-- Revenue................35%
-- Units Sold.............25%
-- Customer Reviews.......20%
-- Freight Efficiency.....10%
-- Category Performance...10%
-- =============================================================================

WITH product_summary AS
(
    SELECT
        pr.product,
        pr.revenue,
        ps.units_sold,
        prev.review_score,
        pf.average_freight_cost,
        cp.category_score

    FROM
    (
        SELECT product_id AS product,
               SUM(price) AS revenue
        FROM order_items
        GROUP BY product_id
    ) pr

    JOIN
    (
        SELECT product_id AS product,
               COUNT(*) AS units_sold
        FROM order_items
        GROUP BY product_id
    ) ps
        ON pr.product = ps.product

    JOIN
    (
        SELECT
            oi.product_id AS product,
            ROUND(AVG(orv.review_score),2) AS review_score
        FROM order_items oi
        JOIN order_reviews orv
            ON oi.order_id = orv.order_id
        GROUP BY oi.product_id
    ) prev
        ON pr.product = prev.product

    JOIN
    (
        SELECT
            product_id AS product,
            ROUND(AVG(freight_value),2) AS average_freight_cost
        FROM order_items
        GROUP BY product_id
    ) pf
        ON pr.product = pf.product

    JOIN
    (
        SELECT
            p.product_id AS product,

            NTILE(100) OVER
            (
                PARTITION BY p.product_category_name
                ORDER BY SUM(oi.price) ASC
            ) AS category_score

        FROM products p

        JOIN order_items oi
            ON p.product_id = oi.product_id

        GROUP BY
            p.product_id,
            p.product_category_name
    ) cp
        ON pr.product = cp.product
),

product_report AS
(
    SELECT

        product,

        NTILE(100) OVER
        (
            ORDER BY revenue ASC
        ) AS revenue_score,

        NTILE(100) OVER
        (
            ORDER BY units_sold ASC
        ) AS sales_score,

        ROUND((review_score / 5.0) * 100,2) AS review_score,

        NTILE(100) OVER
        (
            ORDER BY average_freight_cost DESC
        ) AS freight_score,

        category_score

    FROM product_summary
),

weighted_scorecard AS
(
    SELECT

        product,

        ROUND(revenue_score * 0.35,2) AS weighted_revenue,

        ROUND(sales_score * 0.25,2) AS weighted_sales,

        ROUND(review_score * 0.20,2) AS weighted_reviews,

        ROUND(freight_score * 0.10,2) AS weighted_freight,

        ROUND(category_score * 0.10,2) AS weighted_category,

        ROUND
        (
              revenue_score * 0.35
            + sales_score * 0.25
            + review_score * 0.20
            + freight_score * 0.10
            + category_score * 0.10
        ,2) AS product_performance_score

    FROM product_report
)

SELECT *

FROM weighted_scorecard

ORDER BY product_performance_score DESC;



-- =============================================================================
-- QUESTION 13
-- Classify products according to their overall Product Performance Score.
-- =============================================================================

WITH weighted_scorecard AS
(
    -- Insert Question 12 CTE here
)

SELECT

    product,

    product_performance_score,

    CASE

        WHEN product_performance_score >= 90
            THEN 'Star Product'

        WHEN product_performance_score >= 75
            THEN 'High Performer'

        WHEN product_performance_score >= 60
            THEN 'Growth Product'

        WHEN product_performance_score >= 45
            THEN 'Stable Product'

        ELSE 'Underperforming Product'

    END AS product_classification

FROM weighted_scorecard

ORDER BY product_performance_score DESC;



-- =============================================================================
-- QUESTION 14
-- Display the Top 20 highest-performing products.
-- =============================================================================

WITH product_classification AS
(
    -- Insert Question 13 CTE here
)

SELECT *

FROM product_classification

ORDER BY product_performance_score DESC

LIMIT 20;



-- =============================================================================
-- QUESTION 15
-- Executive KPI Review
--
-- Compare the average KPI scores achieved by each Product Classification.
--
-- This provides management with insight into WHY products fall into each
-- performance category rather than simply showing the final score.
-- =============================================================================

WITH product_report AS
(
    -- Insert Product Report CTE here
),

product_classification AS
(
    -- Insert Question 13 CTE here
)

SELECT

    pc.product_classification,

    ROUND(AVG(pr.revenue_score),2) AS average_revenue_score,

    ROUND(AVG(pr.sales_score),2) AS average_sales_score,

    ROUND(AVG(pr.review_score),2) AS average_review_score,

    ROUND(AVG(pr.freight_score),2) AS average_freight_score,

    ROUND(AVG(pr.category_score),2) AS average_category_score

FROM product_classification pc

JOIN product_report pr

    ON pc.product = pr.product

GROUP BY pc.product_classification

ORDER BY average_revenue_score DESC;



/*
===============================================================================

INVESTIGATION SUMMARY

The Product Portfolio Analysis extends beyond traditional sales reporting by
evaluating products across multiple business dimensions.

Rather than relying solely on revenue, products are assessed using a balanced
scorecard incorporating:

• Financial Performance (Revenue)
• Market Demand (Units Sold)
• Customer Satisfaction (Review Score)
• Operational Efficiency (Freight Cost)
• Competitive Positioning (Category Performance)

To enable meaningful comparison between these diverse metrics, each KPI is
standardized to a common 1–100 scale using PostgreSQL window functions.

Category Performance is evaluated separately by ranking products only against
others within the same category. This prevents products from receiving inflated
scores simply because they belong to a high-revenue category and instead rewards
strong performance relative to direct competitors.

The weighted Product Performance Index provides management with a single,
interpretable score that supports merchandising decisions, pricing strategy,
inventory planning, product promotion, and executive dashboard reporting.

The final scorecard is designed as a reusable analytical dataset suitable for
integration into future Business Intelligence dashboards developed in
Investigation 40.

===============================================================================
*/