/*
===============================================================================
Investigation 38: Delivery Performance & Operational Analysis
SQL File: 32_delivery_performance_operational_analysis.sql

Project : Retail SQL Business Analysis
Database: PostgreSQL

Description
-----------
Analyze seller delivery performance by evaluating delivery duration,
delivery delays, on-time delivery rates, freight costs, customer review
scores, and operational performance using a weighted KPI scorecard.

Tables Used
-----------
- orders
- order_items
- order_reviews
- customers
- products

SQL Concepts
------------
- Aggregate Functions
- INNER JOIN
- LEFT JOIN
- Common Table Expressions (CTEs)
- Window Functions
- Statistical Functions
- CASE Expressions
- COALESCE()
- KPI Standardization
- Weighted Scorecards
===============================================================================
*/

-- =============================================================================
-- Question 1
-- Calculate the average delivery duration for each seller.
-- =============================================================================

WITH seller_delivery AS
(
    SELECT
        oi.seller_id AS seller,
        ROUND(
            AVG(
                EXTRACT(
                    EPOCH FROM (
                        o.order_delivered_customer_date
                        - o.order_purchase_timestamp
                    )
                ) / 86400
            ),
            2
        ) AS avg_delivery_days
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY oi.seller_id
)

SELECT *
FROM seller_delivery
ORDER BY avg_delivery_days;

-- =============================================================================
-- Question 2
-- Calculate the average delivery delay for late deliveries.
-- =============================================================================

WITH seller_delivery_delay AS
(
    SELECT
        oi.seller_id AS seller,
        ROUND(
            AVG(
                EXTRACT(
                    EPOCH FROM (
                        o.order_delivered_customer_date -
                        o.order_estimated_delivery_date
                    )
                ) / 86400
            ),
            2
        ) AS avg_delivery_delay
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
      AND o.order_estimated_delivery_date <
          o.order_delivered_customer_date
    GROUP BY oi.seller_id
)

SELECT *
FROM seller_delivery_delay
ORDER BY avg_delivery_delay;

-- =============================================================================
-- Question 3
-- Calculate the percentage of on-time deliveries for every seller.
-- =============================================================================

WITH total_orders AS
(
    SELECT
        oi.seller_id AS seller,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY oi.seller_id
),

orders_on_time AS
(
    SELECT
        oi.seller_id AS seller,
        COUNT(DISTINCT o.order_id) AS on_time
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
      AND o.order_delivered_customer_date
          <= o.order_estimated_delivery_date
    GROUP BY oi.seller_id
),

delivery_time_analysis AS
(
    SELECT
        tor.seller,
        tor.total_orders,
        COALESCE(oot.on_time, 0) AS on_time,

        ROUND(
            COALESCE(oot.on_time, 0)::NUMERIC
            /
            tor.total_orders
            * 100,
            2
        ) AS on_time_percentage

    FROM total_orders tor

    LEFT JOIN orders_on_time oot
        ON tor.seller = oot.seller
)

SELECT *
FROM delivery_time_analysis;

-- =============================================================================
-- Question 4
-- Calculate the average customer review score for each seller.
-- =============================================================================

WITH seller_reviews AS
(
    SELECT

        oi.seller_id AS seller,
        ROUND(
            AVG(orv.review_score),
            2
        ) AS average_review_score
    FROM order_items AS oi
    JOIN orders AS o
        ON oi.order_id = o.order_id
    JOIN order_reviews AS orv
        ON oi.order_id = orv.order_id
    WHERE
        o.order_status = 'delivered'
    GROUP BY
        oi.seller_id
)

SELECT *
FROM seller_reviews;

-- =============================================================================
-- Question 5
-- Calculate total freight charges generated by each seller.
-- =============================================================================

WITH seller_freight_charges AS
(
    SELECT
        oi.seller_id AS seller,
        SUM(oi.freight_value)
        AS average_freight_cost
    FROM order_items AS oi
    JOIN orders AS o
        ON oi.order_id = o.order_id
    WHERE
        o.order_status = 'delivered'
    GROUP BY
        oi.seller_id
)

SELECT *
FROM seller_freight_charges;


/*==============================================================
Question 6
Average delivery time by customer state
==============================================================*/

WITH state_delivery AS
(
    SELECT
        c.customer_state,
        ROUND(
            AVG(
                EXTRACT(
                    EPOCH FROM
                    (
                        o.order_delivered_customer_date -
                        o.order_purchase_timestamp
                    )
                ) / 86400
            ),
            2
        ) AS avg_delivery_days
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    WHERE o.order_status = 'delivered'
    GROUP BY c.customer_state
)

SELECT *
FROM state_delivery
ORDER BY avg_delivery_days DESC;


/*==============================================================
Question 7
Average delivery time by product category
==============================================================*/

WITH category_delivery AS
(
    SELECT
        p.product_category_name AS category,
        ROUND(
            AVG(
                EXTRACT(
                    EPOCH FROM
                    (
                        o.order_delivered_customer_date -
                        o.order_purchase_timestamp
                    )
                ) / 86400
            ),
            2
        ) AS avg_delivery_days
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    JOIN products p
        ON oi.product_id = p.product_id
    WHERE o.order_status = 'delivered'
    GROUP BY p.product_category_name
)

SELECT *
FROM category_delivery
ORDER BY avg_delivery_days DESC;


/*==============================================================
Question 8
Rank sellers by on-time delivery percentage
==============================================================*/

WITH total_orders AS
(
    SELECT
        oi.seller_id AS seller,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY oi.seller_id
),

orders_on_time AS
(
    SELECT
        oi.seller_id AS seller,
        COUNT(DISTINCT o.order_id) AS on_time
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
      AND o.order_delivered_customer_date <=
          o.order_estimated_delivery_date
    GROUP BY oi.seller_id
),

delivery_time_analysis AS
(
    SELECT
        tor.seller,
        tor.total_orders,
        COALESCE(oot.on_time, 0) AS on_time,

        ROUND(
            COALESCE(oot.on_time, 0)::NUMERIC
            /
            tor.total_orders * 100,
            2
        ) AS on_time_percentage

    FROM total_orders tor
    LEFT JOIN orders_on_time oot
        ON tor.seller = oot.seller
),

on_time_analysis AS
(
    SELECT
        *,
        RANK() OVER
        (
            ORDER BY on_time_percentage DESC
        ) AS on_time_rank
    FROM delivery_time_analysis
)

SELECT *
FROM on_time_analysis;


/*==============================================================
Question 9
Rank sellers by average delivery delay
==============================================================*/

WITH seller_delivery_delay AS
(
    SELECT
        oi.seller_id AS seller,

        ROUND(
            AVG(
                EXTRACT
                (
                    EPOCH FROM
                    (
                        o.order_delivered_customer_date -
                        o.order_estimated_delivery_date
                    )
                ) / 86400
            ),
            2
        ) AS avg_delivery_delay

    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id

    WHERE o.order_status = 'delivered'
      AND o.order_estimated_delivery_date <
          o.order_delivered_customer_date

    GROUP BY oi.seller_id
),

delay_rank AS
(
    SELECT
        *,
        RANK() OVER
        (
            ORDER BY avg_delivery_delay DESC
        ) AS delay_rank
    FROM seller_delivery_delay
)

SELECT *
FROM delay_rank;


/*==============================================================
Question 10
Relationship between delivery delays and review scores
==============================================================*/

WITH seller_delivery_delay AS
(
    SELECT
        oi.seller_id AS seller,

        ROUND(
            AVG(
                EXTRACT
                (
                    EPOCH FROM
                    (
                        o.order_delivered_customer_date -
                        o.order_estimated_delivery_date
                    )
                ) / 86400
            ),
            2
        ) AS avg_delivery_delay

    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id

    WHERE o.order_status = 'delivered'
      AND o.order_estimated_delivery_date <
          o.order_delivered_customer_date

    GROUP BY oi.seller_id
),

delay_rank AS
(
    SELECT
        *,
        RANK() OVER
        (
            ORDER BY avg_delivery_delay DESC
        ) AS delay_rank
    FROM seller_delivery_delay
),

seller_reviews AS
(
    SELECT
        oi.seller_id AS seller,

        ROUND(
            AVG(orv.review_score),
            2
        ) AS average_review_score

    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    JOIN order_reviews orv
        ON oi.order_id = orv.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY oi.seller_id
),

delivery_and_review_analysis AS
(
    SELECT
        dr.seller,
        dr.avg_delivery_delay,
        dr.delay_rank,
        sr.average_review_score

    FROM delay_rank dr
    JOIN seller_reviews sr
        ON dr.seller = sr.seller
)

SELECT *
FROM delivery_and_review_analysis
ORDER BY avg_delivery_delay DESC;


/*==============================================================
Optional Statistical Correlation
==============================================================*/

WITH seller_delivery_delay AS
(
    SELECT
        oi.seller_id AS seller,

        ROUND(
            AVG(
                EXTRACT
                (
                    EPOCH FROM
                    (
                        o.order_delivered_customer_date -
                        o.order_estimated_delivery_date
                    )
                ) / 86400
            ),
            2
        ) AS avg_delivery_delay

    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id

    WHERE o.order_status = 'delivered'
      AND o.order_estimated_delivery_date <
          o.order_delivered_customer_date

    GROUP BY oi.seller_id
),

seller_reviews AS
(
    SELECT
        oi.seller_id AS seller,

        ROUND(
            AVG(orv.review_score),
            2
        ) AS average_review_score

    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    JOIN order_reviews orv
        ON oi.order_id = orv.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY oi.seller_id
),

delivery_and_review_analysis AS
(
    SELECT
        sdd.seller,
        sdd.avg_delivery_delay,
        sr.average_review_score

    FROM seller_delivery_delay sdd
    JOIN seller_reviews sr
        ON sdd.seller = sr.seller
)

SELECT
    CORR(
        avg_delivery_delay,
        average_review_score
    ) AS correlation
FROM delivery_and_review_analysis;


/*==============================================================
Question 11
Create a consolidated seller delivery performance summary
==============================================================*/

WITH seller_delivery AS
(
    SELECT
        oi.seller_id AS seller,
        ROUND(
            AVG(
                EXTRACT(
                    EPOCH FROM
                    (
                        o.order_delivered_customer_date -
                        o.order_purchase_timestamp
                    )
                ) / 86400
            ),
            2
        ) AS avg_delivery_days
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY oi.seller_id
),

total_orders AS
(
    SELECT
        oi.seller_id AS seller,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY oi.seller_id
),

orders_on_time AS
(
    SELECT
        oi.seller_id AS seller,
        COUNT(DISTINCT o.order_id) AS on_time
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
      AND o.order_delivered_customer_date <=
          o.order_estimated_delivery_date
    GROUP BY oi.seller_id
),

delivery_time_analysis AS
(
    SELECT
        tor.seller,
        tor.total_orders,
        COALESCE(oot.on_time,0) AS on_time,

        ROUND(
            COALESCE(oot.on_time,0)::NUMERIC /
            tor.total_orders * 100,
            2
        ) AS on_time_percentage

    FROM total_orders tor

    LEFT JOIN orders_on_time oot
        ON tor.seller = oot.seller
),

seller_reviews AS
(
    SELECT
        oi.seller_id AS seller,

        ROUND(
            AVG(orv.review_score),
            2
        ) AS average_review_score

    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    JOIN order_reviews orv
        ON oi.order_id = orv.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY oi.seller_id
),

seller_freight_charges AS
(
    SELECT
        oi.seller_id AS seller,
        SUM(oi.freight_value) AS average_freight_cost

    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id

    WHERE o.order_status = 'delivered'

    GROUP BY oi.seller_id
),

delivery_performance_summary AS
(
    SELECT
        sd.seller,
        dta.on_time_percentage,
        sd.avg_delivery_days,
        srv.average_review_score,
        sfc.average_freight_cost

    FROM seller_delivery sd

    JOIN delivery_time_analysis dta
        ON sd.seller = dta.seller

    JOIN seller_reviews srv
        ON sd.seller = srv.seller

    JOIN seller_freight_charges sfc
        ON sd.seller = sfc.seller
)

SELECT *
FROM delivery_performance_summary;


/*==============================================================
Question 12
Build Delivery Performance KPI Scorecard
==============================================================*/

WITH seller_delivery AS
(
    SELECT
        oi.seller_id AS seller,
        ROUND(
            AVG(
                EXTRACT(
                    EPOCH FROM
                    (
                        o.order_delivered_customer_date -
                        o.order_purchase_timestamp
                    )
                ) / 86400
            ),
            2
        ) AS avg_delivery_days
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY oi.seller_id
),

total_orders AS
(
    SELECT
        oi.seller_id AS seller,
        COUNT(DISTINCT o.order_id) AS total_orders
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY oi.seller_id
),

orders_on_time AS
(
    SELECT
        oi.seller_id AS seller,
        COUNT(DISTINCT o.order_id) AS on_time
    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    WHERE o.order_status = 'delivered'
      AND o.order_delivered_customer_date <=
          o.order_estimated_delivery_date
    GROUP BY oi.seller_id
),

delivery_time_analysis AS
(
    SELECT
        tor.seller,
        tor.total_orders,

        ROUND(
            COALESCE(oot.on_time,0)::NUMERIC /
            tor.total_orders * 100,
            2
        ) AS on_time_score

    FROM total_orders tor

    LEFT JOIN orders_on_time oot
        ON tor.seller = oot.seller
),

seller_reviews AS
(
    SELECT
        oi.seller_id AS seller,
        ROUND(AVG(orv.review_score),2) AS average_review_score

    FROM order_items oi
    JOIN orders o
        ON oi.order_id = o.order_id
    JOIN order_reviews orv
        ON oi.order_id = orv.order_id

    WHERE o.order_status='delivered'

    GROUP BY oi.seller_id
),

seller_freight_charges AS
(
    SELECT
        oi.seller_id AS seller,
        SUM(oi.freight_value) AS average_freight_cost

    FROM order_items oi
    JOIN orders o
        ON oi.order_id=o.order_id

    WHERE o.order_status='delivered'

    GROUP BY oi.seller_id
),

delivery_performance_summary AS
(
    SELECT
        sd.seller,
        dta.on_time_score,
        sd.avg_delivery_days,
        srv.average_review_score,
        sfc.average_freight_cost

    FROM seller_delivery sd
    JOIN delivery_time_analysis dta
        ON sd.seller=dta.seller
    JOIN seller_reviews srv
        ON sd.seller=srv.seller
    JOIN seller_freight_charges sfc
        ON sd.seller=sfc.seller
),

kpi_standardization AS
(
    SELECT
        seller,

        on_time_score,

        NTILE(100)
        OVER(
            ORDER BY avg_delivery_days DESC
        ) AS delivery_score,

        ROUND(
            (average_review_score/5)*100,
            2
        ) AS review_score,

        NTILE(100)
        OVER(
            ORDER BY average_freight_cost DESC
        ) AS freight_score

    FROM delivery_performance_summary
),

weighted_kpi AS
(
    SELECT
        seller,

        ROUND(0.40*on_time_score,2) AS w_on_time,
        ROUND(0.25*delivery_score,2) AS w_delivery,
        ROUND(0.20*review_score,2) AS w_review,
        ROUND(0.15*freight_score,2) AS w_freight,

        (
            ROUND(0.40*on_time_score,2)+
            ROUND(0.25*delivery_score,2)+
            ROUND(0.20*review_score,2)+
            ROUND(0.15*freight_score,2)
        ) AS delivery_summary

    FROM kpi_standardization
)

SELECT *
FROM weighted_kpi;


/*==============================================================
Question 13
Classify seller delivery performance
==============================================================*/

WITH weighted_kpi AS
(
    ...
),

delivery_classification AS
(
    SELECT
        seller,
        delivery_summary,

        CASE
            WHEN delivery_summary >= 90
                THEN 'Operational Excellence'

            WHEN delivery_summary >= 75
                THEN 'Reliable'

            WHEN delivery_summary >= 60
                THEN 'Needs Monitoring'

            WHEN delivery_summary >= 45
                THEN 'High Risk'

            ELSE 'Critical Risk'
        END AS delivery_class

    FROM weighted_kpi
)

SELECT *
FROM delivery_classification;


/*==============================================================
Question 14
Top performing sellers by delivery score
==============================================================*/

WITH weighted_kpi AS
(
    ...
),

delivery_classification AS
(
    ...
)

SELECT *
FROM delivery_classification
ORDER BY delivery_summary DESC
LIMIT 20;


/*==============================================================
Question 15
Average KPI values by delivery classification
==============================================================*/

WITH kpi_standardization AS
(
    ...
),

weighted_kpi AS
(
    ...
),

delivery_classification AS
(
    ...
),

category_analysis AS
(
    SELECT
        dc.delivery_class,

        ROUND(
            AVG(ks.on_time_score),
            2
        ) AS on_time,

        ROUND(
            AVG(ks.delivery_score),
            2
        ) AS delivery,

        ROUND(
            AVG(ks.review_score),
            2
        ) AS reviews,

        ROUND(
            AVG(ks.freight_score),
            2
        ) AS freight

    FROM delivery_classification dc

    JOIN kpi_standardization ks
        ON dc.seller = ks.seller

    GROUP BY dc.delivery_class
)

SELECT *
FROM category_analysis;

